In [1]:
import pandas as pd
print(pd.__version__)

2.3.2

In [2]:
# series is a basic one dimensional labeled collection of data in pandas
# the data looks like it has index and the related value to it
marks = pd.Series([85,90,79,99,100])
print(marks)

0     85
1     90
2     79
3     99
4    100
dtype: int64

In [3]:
#in series we can give the custom indexes also
marks = pd.Series([85,90,88,99], index=["python","SQL","Excel","PowerBI"])
print(marks)

python     85
SQL        90
Excel      88
PowerBI    99
dtype: int64

In [4]:
#we can access th data using the custom indexes also 
print(marks["python"])

85

In [5]:
# data frame is basically a table, it has collection of series with same index
emp = {
    "Name" :["Hemanth","karthik", "Ganesh"],
    "Age" : [21,25,22],
    "salary" : [40000,50000,60000]
}
df = pd.DataFrame(emp)
print(df)

      Name  Age  salary
0  Hemanth   21   40000
1  karthik   25   50000
2   Ganesh   22   60000

In [6]:
df = pd.DataFrame( 
    emp,
    index = [101,102,103]
)
print(df)

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000
103   Ganesh   22   60000

In [7]:
print(df.shape)

(3, 3)

In [8]:
print(df.columns)

Index(['Name', 'Age', 'salary'], dtype='object')

In [9]:
print(df.index)

Index([101, 102, 103], dtype='int64')

In [10]:
print(df.dtypes)

Name      object
Age        int64
salary     int64
dtype: object

In [11]:
df.head()

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000
103   Ganesh   22   60000

In [12]:
df.head(2)

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000

In [13]:
df.tail()

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000
103   Ganesh   22   60000

In [14]:
df.tail(2)

        Name  Age  salary
102  karthik   25   50000
103   Ganesh   22   60000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 101 to 103
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 96.0+ bytes

In [16]:
df.describe()

             Age   salary
count   3.000000      3.0
mean   22.666667  50000.0
std     2.081666  10000.0
min    21.000000  40000.0
25%    21.500000  45000.0
50%    22.000000  50000.0
75%    23.500000  55000.0
max    25.000000  60000.0

In [18]:
marks = pd.Series([85,90,79,99,100])
print(marks)

0     85
1     90
2     79
3     99
4    100
dtype: int64

In [19]:
print(marks.mean())

90.6

In [20]:
print(marks.median())

90.0

In [21]:
print(marks.mode())

0     79
1     85
2     90
3     99
4    100
dtype: int64

In [22]:
print(marks.describe())

count      5.000000
mean      90.600000
std        9.016651
min       79.000000
25%       85.000000
50%       90.000000
75%       99.000000
max      100.000000
dtype: float64

In [23]:
print(marks.idxmax())

4

In [24]:
print(marks.idxmin())

2

In [27]:
print(marks.nlargest(4))

4    100
3     99
1     90
0     85
dtype: int64

In [28]:
print(marks.nsmallest(3))

2    79
0    85
1    90
dtype: int64

In [38]:
import numpy as np
arr = np.array([["101","102","103"],[22,23,24],[20000,30000,40000]])
print(arr)

[['101' '102' '103']
 ['22' '23' '24']
 ['20000' '30000' '40000']]

In [45]:
dataa = pd.DataFrame(
    arr,
    columns= ["EMPID","Age","Salay"]
)

In [46]:
print(dataa)

   EMPID    Age  Salay
0    101    102    103
1     22     23     24
2  20000  30000  40000

In [2]:
df = pd.DataFrame({
    "org_name": ["google", "oracle", "infosys", "jp morgan", "deloitte"],
    "dept": ["IT", "HR", "SALES", "MARKETING", "MANAGING"],
    "type": ["product", "product", "service", "service", "service"],
    "salary": [100000, 80000, 50000, 90000, 35000]
}, index=["c1", "c2", "c3", "c4", "c5"])

In [3]:
print(df[df["dept"].isin(["IT", "MANAGING"])]["org_name"])

c1      google
c5    deloitte
Name: org_name, dtype: object

In [4]:
df[df["type"] == "product"]

   org_name dept     type  salary
c1   google   IT  product  100000
c2   oracle   HR  product   80000

In [5]:
df[df["dept"].isin(["IT", "MANAGING"])]["org_name"]

c1      google
c5    deloitte
Name: org_name, dtype: object

In [6]:
df[df["salary"].between(50000, 100000, inclusive="neither")]

     org_name       dept     type  salary
c2     oracle         HR  product   80000
c4  jp morgan  MARKETING  service   90000

In [7]:
print(df.query("dept == 'IT'"))

   org_name dept     type  salary
c1   google   IT  product  100000

In [2]:
data = pd.read_csv("./orders.csv")
print(data)

   OrderID        Date CustomerID                  ProductName   Cost  \
0   ORD001  2026-01-05    CUST001                       Laptop  65000
1   ORD002  2026-01-06    CUST002               Wireless Mouse   1200
2   ORD003  2026-01-07    CUST003                     Keyboard   2500
3   ORD004  2026-01-08    CUST004                      Monitor  18500
4   ORD005  2026-01-09    CUST005                   Headphones   3500
5   ORD006  2026-01-10    CUST006                    USB Cable    650
6   ORD007  2026-01-11    CUST007                       Webcam   4200
7   ORD008  2026-01-12    CUST008                 External SSD   7800
8   ORD009  2026-01-13    CUST009                   Smartphone  42000
9   ORD010  2026-01-14    CUST010                   Power Bank   1800
10  ORD011  2026-01-15    CUST011                 Laptop Stand   2200
11  ORD012  2026-01-16    CUST012          Mechanical Keyboard   5500
12  ORD013  2026-01-17    CUST013            Bluetooth Speaker   3200
13  ORD014  2026-01-18    CUST014                       Tablet  28000
14  ORD015  2026-01-19    CUST015                  Smart Watch   8500
15  ORD016  2026-01-20    CUST016             Wireless Earbuds   4500
16  ORD017  2026-01-21    CUST017                   HDMI Cable    900
17  ORD018  2026-01-22    CUST018                    Desk Lamp   1600
18  ORD019  2026-01-23    CUST019                 Office Chair  12500
19  ORD020  2026-01-24    CUST020                    Mouse Pad    750
20  ORD021  2026-01-25    CUST021                   Laptop Bag   2800
21  ORD022  2026-01-26    CUST022                      Printer  15500
22  ORD023  2026-01-27    CUST023                Ink Cartridge   1800
23  ORD024  2026-01-28    CUST024                       Router   4200
24  ORD025  2026-01-29    CUST025              Smartphone Case    950
25  ORD026  2026-01-30    CUST026             Screen Protector    500
26  ORD027  2026-02-01    CUST027                Power Adapter   2400
27  ORD028  2026-02-02    CUST028          Portable Hard Drive   6200
28  ORD029  2026-02-03    CUST029            Gaming Controller   4800
29  ORD030  2026-02-04    CUST030                   Microphone   6500
30  ORD031  2026-02-05    CUST031                     Smart TV  52000
31  ORD032  2026-02-06    CUST032                     Soundbar  14500
32  ORD033  2026-02-07    CUST033                      USB Hub   1800
33  ORD034  2026-02-08    CUST034              Graphics Tablet   7200
34  ORD035  2026-02-09    CUST035                WiFi Extender   2800
35  ORD036  2026-02-10    CUST036                 Air Purifier  11500
36  ORD037  2026-02-11    CUST037                   Smart Bulb    850
37  ORD038  2026-02-12    CUST038                  Power Strip   1400
38  ORD039  2026-02-13    CUST039                  DSLR Camera  68000
39  ORD040  2026-02-14    CUST040                Camera Tripod   3500
40  ORD041  2026-02-15    CUST041                  Memory Card   1600
41  ORD042  2026-02-16    CUST042             Smartwatch Strap    900
42  ORD043  2026-02-17    CUST043                   VR Headset  32000
43  ORD044  2026-02-18    CUST044                    Projector  27500
44  ORD045  2026-02-19    CUST045             Projector Screen   6500
45  ORD046  2026-02-20    CUST046  Noise Cancelling Headphones   9200
46  ORD047  2026-02-21    CUST047              USB Flash Drive   1100
47  ORD048  2026-02-22    CUST048               Smart Doorbell   7800
48  ORD049  2026-02-23    CUST049              Security Camera   6500
49  ORD050  2026-02-24    CUST050               Smart Home Hub   5500

    Quantity
0          1
1          2
2          1
3          1
4          2
5          3
6          1
7          1
8          1
9          2
10         1
11         1
12         2
13         1
14         1
15         2
16         3
17         1
18         1
19         2
20         1
21         1
22         2
23         1
24         2
25         3
26         1
27         1
28         2
29         1
30         1
31         1
32         2
33         1
34         1
35         1
36         4
37         2
38         1
39         1
40         2
41         3
42         1
43         1
44         1
45         1
46         4
47         1
48         2
49         1

In [3]:
print(data.shape)

(50, 6)

In [19]:
print(data.tail())

   OrderID        Date CustomerID                  ProductName  Cost  Quantity
45  ORD046  2026-02-20    CUST046  Noise Cancelling Headphones  9200         1
46  ORD047  2026-02-21    CUST047              USB Flash Drive  1100         4
47  ORD048  2026-02-22    CUST048               Smart Doorbell  7800         1
48  ORD049  2026-02-23    CUST049              Security Camera  6500         2
49  ORD050  2026-02-24    CUST050               Smart Home Hub  5500         1

In [20]:
print(data.head())

  OrderID        Date CustomerID     ProductName   Cost  Quantity
0  ORD001  2026-01-05    CUST001          Laptop  65000         1
1  ORD002  2026-01-06    CUST002  Wireless Mouse   1200         2
2  ORD003  2026-01-07    CUST003        Keyboard   2500         1
3  ORD004  2026-01-08    CUST004         Monitor  18500         1
4  ORD005  2026-01-09    CUST005      Headphones   3500         2

In [22]:
print(data.sample())

   OrderID        Date CustomerID ProductName   Cost  Quantity
42  ORD043  2026-02-17    CUST043  VR Headset  32000         1

In [4]:
print(data.columns)

Index(['OrderID', 'Date', 'CustomerID', 'ProductName', 'Cost', 'Quantity'], dtype='object')

In [15]:
dual_order = data[data["Quantity"] > 1]
print(dual_order)

   OrderID        Date CustomerID        ProductName  Cost  Quantity
1   ORD002  2026-01-06    CUST002     Wireless Mouse  1200         2
4   ORD005  2026-01-09    CUST005         Headphones  3500         2
5   ORD006  2026-01-10    CUST006          USB Cable   650         3
9   ORD010  2026-01-14    CUST010         Power Bank  1800         2
12  ORD013  2026-01-17    CUST013  Bluetooth Speaker  3200         2
15  ORD016  2026-01-20    CUST016   Wireless Earbuds  4500         2
16  ORD017  2026-01-21    CUST017         HDMI Cable   900         3
19  ORD020  2026-01-24    CUST020          Mouse Pad   750         2
22  ORD023  2026-01-27    CUST023      Ink Cartridge  1800         2
24  ORD025  2026-01-29    CUST025    Smartphone Case   950         2
25  ORD026  2026-01-30    CUST026   Screen Protector   500         3
28  ORD029  2026-02-03    CUST029  Gaming Controller  4800         2
32  ORD033  2026-02-07    CUST033            USB Hub  1800         2
36  ORD037  2026-02-11    CUST037         Smart Bulb   850         4
37  ORD038  2026-02-12    CUST038        Power Strip  1400         2
40  ORD041  2026-02-15    CUST041        Memory Card  1600         2
41  ORD042  2026-02-16    CUST042   Smartwatch Strap   900         3
46  ORD047  2026-02-21    CUST047    USB Flash Drive  1100         4
48  ORD049  2026-02-23    CUST049    Security Camera  6500         2

In [17]:
print(data.describe())

            Cost   Quantity
count     50.000  50.000000
mean   10452.000   1.540000
std    15795.992   0.813408
min      500.000   1.000000
25%     1800.000   1.000000
50%     4350.000   1.000000
75%     9025.000   2.000000
max    68000.000   4.000000

In [27]:
print(data["Quantity"].sum())

77

In [31]:
print(data["Cost"].max())

68000

In [33]:
print(data.loc[data["Cost"].idxmax()])

OrderID             ORD039
Date            2026-02-13
CustomerID         CUST039
ProductName    DSLR Camera
Cost                 68000
Quantity                 1
Name: 38, dtype: object

In [35]:
print(data[data["Cost"] == data["Cost"].max()])

   OrderID        Date CustomerID  ProductName   Cost  Quantity
38  ORD039  2026-02-13    CUST039  DSLR Camera  68000         1

In [38]:
print(data.sort_values("Cost"))

   OrderID        Date CustomerID                  ProductName   Cost  \
25  ORD026  2026-01-30    CUST026             Screen Protector    500
5   ORD006  2026-01-10    CUST006                    USB Cable    650
19  ORD020  2026-01-24    CUST020                    Mouse Pad    750
36  ORD037  2026-02-11    CUST037                   Smart Bulb    850
16  ORD017  2026-01-21    CUST017                   HDMI Cable    900
41  ORD042  2026-02-16    CUST042             Smartwatch Strap    900
24  ORD025  2026-01-29    CUST025              Smartphone Case    950
46  ORD047  2026-02-21    CUST047              USB Flash Drive   1100
1   ORD002  2026-01-06    CUST002               Wireless Mouse   1200
37  ORD038  2026-02-12    CUST038                  Power Strip   1400
40  ORD041  2026-02-15    CUST041                  Memory Card   1600
17  ORD018  2026-01-22    CUST018                    Desk Lamp   1600
22  ORD023  2026-01-27    CUST023                Ink Cartridge   1800
32  ORD033  2026-02-07    CUST033                      USB Hub   1800
9   ORD010  2026-01-14    CUST010                   Power Bank   1800
10  ORD011  2026-01-15    CUST011                 Laptop Stand   2200
26  ORD027  2026-02-01    CUST027                Power Adapter   2400
2   ORD003  2026-01-07    CUST003                     Keyboard   2500
20  ORD021  2026-01-25    CUST021                   Laptop Bag   2800
34  ORD035  2026-02-09    CUST035                WiFi Extender   2800
12  ORD013  2026-01-17    CUST013            Bluetooth Speaker   3200
39  ORD040  2026-02-14    CUST040                Camera Tripod   3500
4   ORD005  2026-01-09    CUST005                   Headphones   3500
6   ORD007  2026-01-11    CUST007                       Webcam   4200
23  ORD024  2026-01-28    CUST024                       Router   4200
15  ORD016  2026-01-20    CUST016             Wireless Earbuds   4500
28  ORD029  2026-02-03    CUST029            Gaming Controller   4800
49  ORD050  2026-02-24    CUST050               Smart Home Hub   5500
11  ORD012  2026-01-16    CUST012          Mechanical Keyboard   5500
27  ORD028  2026-02-02    CUST028          Portable Hard Drive   6200
48  ORD049  2026-02-23    CUST049              Security Camera   6500
29  ORD030  2026-02-04    CUST030                   Microphone   6500
44  ORD045  2026-02-19    CUST045             Projector Screen   6500
33  ORD034  2026-02-08    CUST034              Graphics Tablet   7200
7   ORD008  2026-01-12    CUST008                 External SSD   7800
47  ORD048  2026-02-22    CUST048               Smart Doorbell   7800
14  ORD015  2026-01-19    CUST015                  Smart Watch   8500
45  ORD046  2026-02-20    CUST046  Noise Cancelling Headphones   9200
35  ORD036  2026-02-10    CUST036                 Air Purifier  11500
18  ORD019  2026-01-23    CUST019                 Office Chair  12500
31  ORD032  2026-02-06    CUST032                     Soundbar  14500
21  ORD022  2026-01-26    CUST022                      Printer  15500
3   ORD004  2026-01-08    CUST004                      Monitor  18500
43  ORD044  2026-02-18    CUST044                    Projector  27500
13  ORD014  2026-01-18    CUST014                       Tablet  28000
42  ORD043  2026-02-17    CUST043                   VR Headset  32000
8   ORD009  2026-01-13    CUST009                   Smartphone  42000
30  ORD031  2026-02-05    CUST031                     Smart TV  52000
0   ORD001  2026-01-05    CUST001                       Laptop  65000
38  ORD039  2026-02-13    CUST039                  DSLR Camera  68000

    Quantity
25         3
5          3
19         2
36         4
16         3
41         3
24         2
46         4
1          2
37         2
40         2
17         1
22         2
32         2
9          2
10         1
26         1
2          1
20         1
34         1
12         2
39         1
4          2
6          1
23         1
15         2
28         2
49         1
11         1
27         1
48         2
29         1
44         1
33         1
7          1
47         1
14         1
45         1
35         1
18         1
31         1
21         1
3          1
43         1
13         1
42         1
8          1
30         1
0          1
38         1

In [11]:
data = pd.read_csv("./orders.csv")
print(data)

   Order_ID  Order_Date Customer_ID                      Product  \
0    ORD001  2026-01-05     CUST001                       Laptop
1    ORD002  2026-01-06     CUST002               Wireless Mouse
2    ORD003  2026-01-07     CUST003                     Keyboard
3    ORD004  2026-01-08     CUST004                      Monitor
4    ORD005  2026-01-09     CUST005                   Headphones
5    ORD006  2026-01-10     CUST006                    USB Cable
6    ORD007  2026-01-11     CUST007                       Webcam
7    ORD008  2026-01-12     CUST008                 External SSD
8    ORD009  2026-01-13     CUST009                   Smartphone
9    ORD010  2026-01-14     CUST010                   Power Bank
10   ORD011  2026-01-15     CUST011                 Laptop Stand
11   ORD012  2026-01-16     CUST012          Mechanical Keyboard
12   ORD013  2026-01-17     CUST013            Bluetooth Speaker
13   ORD014  2026-01-18     CUST014                       Tablet
14   ORD015  2026-01-19     CUST015                  Smart Watch
15   ORD016  2026-01-20     CUST016             Wireless Earbuds
16   ORD017  2026-01-21     CUST017                   HDMI Cable
17   ORD018  2026-01-22     CUST018                    Desk Lamp
18   ORD019  2026-01-23     CUST019                 Office Chair
19   ORD020  2026-01-24     CUST020                    Mouse Pad
20   ORD021  2026-01-25     CUST021                   Laptop Bag
21   ORD022  2026-01-26     CUST022                      Printer
22   ORD023  2026-01-27     CUST023                Ink Cartridge
23   ORD024  2026-01-28     CUST024                       Router
24   ORD025  2026-01-29     CUST025              Smartphone Case
25   ORD026  2026-01-30     CUST026             Screen Protector
26   ORD027  2026-02-01     CUST027                Power Adapter
27   ORD028  2026-02-02     CUST028          Portable Hard Drive
28   ORD029  2026-02-03     CUST029            Gaming Controller
29   ORD030  2026-02-04     CUST030                   Microphone
30   ORD031  2026-02-05     CUST031                     Smart TV
31   ORD032  2026-02-06     CUST032                     Soundbar
32   ORD033  2026-02-07     CUST033                      USB Hub
33   ORD034  2026-02-08     CUST034              Graphics Tablet
34   ORD035  2026-02-09     CUST035                WiFi Extender
35   ORD036  2026-02-10     CUST036                 Air Purifier
36   ORD037  2026-02-11     CUST037                   Smart Bulb
37   ORD038  2026-02-12     CUST038                  Power Strip
38   ORD039  2026-02-13     CUST039                  DSLR Camera
39   ORD040  2026-02-14     CUST040                Camera Tripod
40   ORD041  2026-02-15     CUST041                  Memory Card
41   ORD042  2026-02-16     CUST042             Smartwatch Strap
42   ORD043  2026-02-17     CUST043                   VR Headset
43   ORD044  2026-02-18     CUST044                    Projector
44   ORD045  2026-02-19     CUST045             Projector Screen
45   ORD046  2026-02-20     CUST046  Noise Cancelling Headphones
46   ORD047  2026-02-21     CUST047              USB Flash Drive
47   ORD048  2026-02-22     CUST048               Smart Doorbell
48   ORD049  2026-02-23     CUST049              Security Camera
49   ORD050  2026-02-24     CUST050               Smart Home Hub

              Category  Quantity  Price       City
0          Electronics       1.0  65000  Hyderabad
1          Accessories       2.0   1200  Bangalore
2          Accessories       1.0   2500    Chennai
3          Electronics       1.0  18500     Mumbai
4                Audio       2.0   3500      Delhi
5          Accessories       3.0    650       Pune
6          Electronics       1.0   4200  Hyderabad
7              Storage       NaN   7800  Bangalore
8          Electronics       1.0  42000    Chennai
9          Accessories       2.0   1800     Mumbai
10         Accessories       1.0   2200      Delhi
11         Accessories       1.0   5500       Pune
12               Audio       2.0   3200  Hyderabad
13         Electronics       1.0  28000  Bangalore
14           Wearables       1.0   8500    Chennai
15               Audio       2.0   4500     Mumbai
16         Accessories       3.0    900      Delhi
17       Home & Office       1.0   1600       Pune
18           Furniture       1.0  12500  Hyderabad
19         Accessories       2.0    750  Bangalore
20                Bags       1.0   2800    Chennai
21         Electronics       1.0  15500     Mumbai
22    Printer Supplies       2.0   1800      Delhi
23          Networking       1.0   4200       Pune
24         Accessories       2.0    950  Hyderabad
25         Accessories       3.0    500  Bangalore
26         Accessories       1.0   2400    Chennai
27             Storage       1.0   6200     Mumbai
28              Gaming       2.0   4800      Delhi
29               Audio       1.0   6500       Pune
30         Electronics       1.0  52000  Hyderabad
31               Audio       1.0  14500  Bangalore
32         Accessories       2.0   1800    Chennai
33         Electronics       1.0   7200     Mumbai
34          Networking       1.0   2800      Delhi
35     Home Appliances       1.0  11500       Pune
36          Smart Home       4.0    850  Hyderabad
37         Accessories       2.0   1400  Bangalore
38             Cameras       1.0  68000    Chennai
39  Camera Accessories       1.0   3500     Mumbai
40             Storage       2.0   1600      Delhi
41           Wearables       3.0    900       Pune
42              Gaming       1.0  32000  Hyderabad
43         Electronics       1.0  27500  Bangalore
44       Home & Office       1.0   6500    Chennai
45               Audio       1.0   9200     Mumbai
46             Storage       4.0   1100      Delhi
47          Smart Home       1.0   7800       Pune
48            Security       2.0   6500  Hyderabad
49          Smart Home       1.0   5500  Bangalore

In [4]:
print(data.head())

  Order_ID  Order_Date Customer_ID         Product     Category  Quantity  \
0   ORD001  2026-01-05     CUST001          Laptop  Electronics         1
1   ORD002  2026-01-06     CUST002  Wireless Mouse  Accessories         2
2   ORD003  2026-01-07     CUST003        Keyboard  Accessories         1
3   ORD004  2026-01-08     CUST004         Monitor  Electronics         1
4   ORD005  2026-01-09     CUST005      Headphones        Audio         2

   Price       City
0  65000  Hyderabad
1   1200  Bangalore
2   2500    Chennai
3  18500     Mumbai
4   3500      Delhi

In [5]:
print(data.tail())

   Order_ID  Order_Date Customer_ID                      Product    Category  \
45   ORD046  2026-02-20     CUST046  Noise Cancelling Headphones       Audio
46   ORD047  2026-02-21     CUST047              USB Flash Drive     Storage
47   ORD048  2026-02-22     CUST048               Smart Doorbell  Smart Home
48   ORD049  2026-02-23     CUST049              Security Camera    Security
49   ORD050  2026-02-24     CUST050               Smart Home Hub  Smart Home

    Quantity  Price       City
45         1   9200     Mumbai
46         4   1100      Delhi
47         1   7800       Pune
48         2   6500  Hyderabad
49         1   5500  Bangalore

In [6]:
print(data.sample())

   Order_ID  Order_Date Customer_ID        Product          Category  \
22   ORD023  2026-01-27     CUST023  Ink Cartridge  Printer Supplies

    Quantity  Price   City
22         2   1800  Delhi

In [7]:
print(data.shape)

(50, 8)

In [8]:
print(data.columns)

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product', 'Category',
       'Quantity', 'Price', 'City'],
      dtype='object')

In [12]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     50 non-null     object
 1   Order_Date   50 non-null     object
 2   Customer_ID  50 non-null     object
 3   Product      50 non-null     object
 4   Category     50 non-null     object
 5   Quantity     49 non-null     float64
 6   Price        50 non-null     int64
 7   City         50 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 3.3+ KB
None

In [13]:
print(data.describe())

        Quantity      Price
count  49.000000     50.000
mean    1.551020  10452.000
std     0.818057  15795.992
min     1.000000    500.000
25%     1.000000   1800.000
50%     1.000000   4350.000
75%     2.000000   9025.000
max     4.000000  68000.000

In [15]:
print(data["Product"])

0                          Laptop
1                  Wireless Mouse
2                        Keyboard
3                         Monitor
4                      Headphones
5                       USB Cable
6                          Webcam
7                    External SSD
8                      Smartphone
9                      Power Bank
10                   Laptop Stand
11            Mechanical Keyboard
12              Bluetooth Speaker
13                         Tablet
14                    Smart Watch
15               Wireless Earbuds
16                     HDMI Cable
17                      Desk Lamp
18                   Office Chair
19                      Mouse Pad
20                     Laptop Bag
21                        Printer
22                  Ink Cartridge
23                         Router
24                Smartphone Case
25               Screen Protector
26                  Power Adapter
27            Portable Hard Drive
28              Gaming Controller
29                     Microphone
30                       Smart TV
31                       Soundbar
32                        USB Hub
33                Graphics Tablet
34                  WiFi Extender
35                   Air Purifier
36                     Smart Bulb
37                    Power Strip
38                    DSLR Camera
39                  Camera Tripod
40                    Memory Card
41               Smartwatch Strap
42                     VR Headset
43                      Projector
44               Projector Screen
45    Noise Cancelling Headphones
46                USB Flash Drive
47                 Smart Doorbell
48                Security Camera
49                 Smart Home Hub
Name: Product, dtype: object

In [17]:
print(data[["Order_ID", "Product", "Quantity"]])

   Order_ID                      Product  Quantity
0    ORD001                       Laptop       1.0
1    ORD002               Wireless Mouse       2.0
2    ORD003                     Keyboard       1.0
3    ORD004                      Monitor       1.0
4    ORD005                   Headphones       2.0
5    ORD006                    USB Cable       3.0
6    ORD007                       Webcam       1.0
7    ORD008                 External SSD       NaN
8    ORD009                   Smartphone       1.0
9    ORD010                   Power Bank       2.0
10   ORD011                 Laptop Stand       1.0
11   ORD012          Mechanical Keyboard       1.0
12   ORD013            Bluetooth Speaker       2.0
13   ORD014                       Tablet       1.0
14   ORD015                  Smart Watch       1.0
15   ORD016             Wireless Earbuds       2.0
16   ORD017                   HDMI Cable       3.0
17   ORD018                    Desk Lamp       1.0
18   ORD019                 Office Chair       1.0
19   ORD020                    Mouse Pad       2.0
20   ORD021                   Laptop Bag       1.0
21   ORD022                      Printer       1.0
22   ORD023                Ink Cartridge       2.0
23   ORD024                       Router       1.0
24   ORD025              Smartphone Case       2.0
25   ORD026             Screen Protector       3.0
26   ORD027                Power Adapter       1.0
27   ORD028          Portable Hard Drive       1.0
28   ORD029            Gaming Controller       2.0
29   ORD030                   Microphone       1.0
30   ORD031                     Smart TV       1.0
31   ORD032                     Soundbar       1.0
32   ORD033                      USB Hub       2.0
33   ORD034              Graphics Tablet       1.0
34   ORD035                WiFi Extender       1.0
35   ORD036                 Air Purifier       1.0
36   ORD037                   Smart Bulb       4.0
37   ORD038                  Power Strip       2.0
38   ORD039                  DSLR Camera       1.0
39   ORD040                Camera Tripod       1.0
40   ORD041                  Memory Card       2.0
41   ORD042             Smartwatch Strap       3.0
42   ORD043                   VR Headset       1.0
43   ORD044                    Projector       1.0
44   ORD045             Projector Screen       1.0
45   ORD046  Noise Cancelling Headphones       1.0
46   ORD047              USB Flash Drive       4.0
47   ORD048               Smart Doorbell       1.0
48   ORD049              Security Camera       2.0
49   ORD050               Smart Home Hub       1.0

In [18]:
print(data[["Customer_ID", "City"]])

   Customer_ID       City
0      CUST001  Hyderabad
1      CUST002  Bangalore
2      CUST003    Chennai
3      CUST004     Mumbai
4      CUST005      Delhi
5      CUST006       Pune
6      CUST007  Hyderabad
7      CUST008  Bangalore
8      CUST009    Chennai
9      CUST010     Mumbai
10     CUST011      Delhi
11     CUST012       Pune
12     CUST013  Hyderabad
13     CUST014  Bangalore
14     CUST015    Chennai
15     CUST016     Mumbai
16     CUST017      Delhi
17     CUST018       Pune
18     CUST019  Hyderabad
19     CUST020  Bangalore
20     CUST021    Chennai
21     CUST022     Mumbai
22     CUST023      Delhi
23     CUST024       Pune
24     CUST025  Hyderabad
25     CUST026  Bangalore
26     CUST027    Chennai
27     CUST028     Mumbai
28     CUST029      Delhi
29     CUST030       Pune
30     CUST031  Hyderabad
31     CUST032  Bangalore
32     CUST033    Chennai
33     CUST034     Mumbai
34     CUST035      Delhi
35     CUST036       Pune
36     CUST037  Hyderabad
37     CUST038  Bangalore
38     CUST039    Chennai
39     CUST040     Mumbai
40     CUST041      Delhi
41     CUST042       Pune
42     CUST043  Hyderabad
43     CUST044  Bangalore
44     CUST045    Chennai
45     CUST046     Mumbai
46     CUST047      Delhi
47     CUST048       Pune
48     CUST049  Hyderabad
49     CUST050  Bangalore

In [20]:
print(data.iloc[0])

Order_ID            ORD001
Order_Date      2026-01-05
Customer_ID        CUST001
Product             Laptop
Category       Electronics
Quantity               1.0
Price                65000
City             Hyderabad
Name: 0, dtype: object

In [21]:
print(data.iloc[:5])

  Order_ID  Order_Date Customer_ID         Product     Category  Quantity  \
0   ORD001  2026-01-05     CUST001          Laptop  Electronics       1.0
1   ORD002  2026-01-06     CUST002  Wireless Mouse  Accessories       2.0
2   ORD003  2026-01-07     CUST003        Keyboard  Accessories       1.0
3   ORD004  2026-01-08     CUST004         Monitor  Electronics       1.0
4   ORD005  2026-01-09     CUST005      Headphones        Audio       2.0

   Price       City
0  65000  Hyderabad
1   1200  Bangalore
2   2500    Chennai
3  18500     Mumbai
4   3500      Delhi

In [ ]:
print(data.iloc[0:10, 0:4]) 
#here we select 0-9 rows and the first 4 columns  from the data

  Order_ID  Order_Date Customer_ID         Product
0   ORD001  2026-01-05     CUST001          Laptop
1   ORD002  2026-01-06     CUST002  Wireless Mouse
2   ORD003  2026-01-07     CUST003        Keyboard
3   ORD004  2026-01-08     CUST004         Monitor
4   ORD005  2026-01-09     CUST005      Headphones
5   ORD006  2026-01-10     CUST006       USB Cable
6   ORD007  2026-01-11     CUST007          Webcam
7   ORD008  2026-01-12     CUST008    External SSD
8   ORD009  2026-01-13     CUST009      Smartphone
9   ORD010  2026-01-14     CUST010      Power Bank

In [ ]:
print(data.loc[0:4, ["Order_ID", "Product", "Price"]])
#since loc is labeled orianted we can select the columns

  Order_ID         Product  Price
0   ORD001          Laptop  65000
1   ORD002  Wireless Mouse   1200
2   ORD003        Keyboard   2500
3   ORD004         Monitor  18500
4   ORD005      Headphones   3500

In [ ]:
#create revenue
# Revenue = Quantity * Price
data["Revenue"] = data["Quantity"] * data["Price"] 
print(data.head())

  Order_ID  Order_Date Customer_ID         Product     Category  Quantity  \
0   ORD001  2026-01-05     CUST001          Laptop  Electronics       1.0
1   ORD002  2026-01-06     CUST002  Wireless Mouse  Accessories       2.0
2   ORD003  2026-01-07     CUST003        Keyboard  Accessories       1.0
3   ORD004  2026-01-08     CUST004         Monitor  Electronics       1.0
4   ORD005  2026-01-09     CUST005      Headphones        Audio       2.0

   Price       City  Revenue
0  65000  Hyderabad  65000.0
1   1200  Bangalore   2400.0
2   2500    Chennai   2500.0
3  18500     Mumbai  18500.0
4   3500      Delhi   7000.0

In [28]:
data.to_csv("orders.csv", index=False)

In [26]:
print(data[["Quantity", "Price", "Revenue"]].head())

   Quantity  Price  Revenue
0       1.0  65000  65000.0
1       2.0   1200   2400.0
2       1.0   2500   2500.0
3       1.0  18500  18500.0
4       2.0   3500   7000.0

In [27]:
high_value = data.loc[data["Revenue"] > 50000]
print(high_value)

   Order_ID  Order_Date Customer_ID      Product     Category  Quantity  \
0    ORD001  2026-01-05     CUST001       Laptop  Electronics       1.0
30   ORD031  2026-02-05     CUST031     Smart TV  Electronics       1.0
38   ORD039  2026-02-13     CUST039  DSLR Camera      Cameras       1.0

    Price       City  Revenue
0   65000  Hyderabad  65000.0
30  52000  Hyderabad  52000.0
38  68000    Chennai  68000.0

In [2]:
data = pd.read_csv("./orders.csv")
print(data)

   Order_ID  Order_Date Customer_ID                      Product  \
0    ORD001  2026-01-05     CUST001                       Laptop
1    ORD002  2026-01-06     CUST002               Wireless Mouse
2    ORD003  2026-01-07     CUST003                     Keyboard
3    ORD004  2026-01-08     CUST004                      Monitor
4    ORD005  2026-01-09     CUST005                   Headphones
5    ORD006  2026-01-10     CUST006                    USB Cable
6    ORD007  2026-01-11     CUST007                       Webcam
7    ORD008  2026-01-12     CUST008                 External SSD
8    ORD009  2026-01-13     CUST009                   Smartphone
9    ORD010  2026-01-14     CUST010                   Power Bank
10   ORD011  2026-01-15     CUST011                 Laptop Stand
11   ORD012  2026-01-16     CUST012          Mechanical Keyboard
12   ORD013  2026-01-17     CUST013            Bluetooth Speaker
13   ORD014  2026-01-18     CUST014                       Tablet
14   ORD015  2026-01-19     CUST015                  Smart Watch
15   ORD016  2026-01-20     CUST016             Wireless Earbuds
16   ORD017  2026-01-21     CUST017                   HDMI Cable
17   ORD018  2026-01-22     CUST018                    Desk Lamp
18   ORD019  2026-01-23     CUST019                 Office Chair
19   ORD020  2026-01-24     CUST020                    Mouse Pad
20   ORD021  2026-01-25     CUST021                   Laptop Bag
21   ORD022  2026-01-26     CUST022                      Printer
22   ORD023  2026-01-27     CUST023                Ink Cartridge
23   ORD024  2026-01-28     CUST024                       Router
24   ORD025  2026-01-29     CUST025              Smartphone Case
25   ORD026  2026-01-30     CUST026             Screen Protector
26   ORD027  2026-02-01     CUST027                Power Adapter
27   ORD028  2026-02-02     CUST028          Portable Hard Drive
28   ORD029  2026-02-03     CUST029            Gaming Controller
29   ORD030  2026-02-04     CUST030                   Microphone
30   ORD031  2026-02-05     CUST031                     Smart TV
31   ORD032  2026-02-06     CUST032                     Soundbar
32   ORD033  2026-02-07     CUST033                      USB Hub
33   ORD034  2026-02-08     CUST034              Graphics Tablet
34   ORD035  2026-02-09     CUST035                WiFi Extender
35   ORD036  2026-02-10     CUST036                 Air Purifier
36   ORD037  2026-02-11     CUST037                   Smart Bulb
37   ORD038  2026-02-12     CUST038                  Power Strip
38   ORD039  2026-02-13     CUST039                  DSLR Camera
39   ORD040  2026-02-14     CUST040                Camera Tripod
40   ORD041  2026-02-15     CUST041                  Memory Card
41   ORD042  2026-02-16     CUST042             Smartwatch Strap
42   ORD043  2026-02-17     CUST043                   VR Headset
43   ORD044  2026-02-18     CUST044                    Projector
44   ORD045  2026-02-19     CUST045             Projector Screen
45   ORD046  2026-02-20     CUST046  Noise Cancelling Headphones
46   ORD047  2026-02-21     CUST047              USB Flash Drive
47   ORD048  2026-02-22     CUST048               Smart Doorbell
48   ORD049  2026-02-23     CUST049              Security Camera
49   ORD050  2026-02-24     CUST050               Smart Home Hub

              Category  Quantity  Price       City  Revenue
0          Electronics       1.0  65000  Hyderabad  65000.0
1          Accessories       2.0   1200  Bangalore   2400.0
2          Accessories       1.0   2500    Chennai   2500.0
3          Electronics       1.0  18500     Mumbai  18500.0
4                Audio       2.0   3500      Delhi   7000.0
5          Accessories       3.0    650       Pune   1950.0
6          Electronics       1.0   4200  Hyderabad   4200.0
7              Storage       NaN   7800  Bangalore      NaN
8          Electronics       1.0  42000    Chennai  42000.0
9          Accessories       2.0   1800     Mumbai   3600.0
10         Accessories       1.0   2200      Delhi   2200.0
11         Accessories       1.0   5500       Pune   5500.0
12               Audio       2.0   3200  Hyderabad   6400.0
13         Electronics       1.0  28000  Bangalore  28000.0
14           Wearables       1.0   8500    Chennai   8500.0
15               Audio       2.0   4500     Mumbai   9000.0
16         Accessories       3.0    900      Delhi   2700.0
17       Home & Office       1.0   1600       Pune   1600.0
18           Furniture       1.0  12500  Hyderabad  12500.0
19         Accessories       2.0    750  Bangalore   1500.0
20                Bags       1.0   2800    Chennai   2800.0
21         Electronics       1.0  15500     Mumbai  15500.0
22    Printer Supplies       2.0   1800      Delhi   3600.0
23          Networking       1.0   4200       Pune   4200.0
24         Accessories       2.0    950  Hyderabad   1900.0
25         Accessories       3.0    500  Bangalore   1500.0
26         Accessories       1.0   2400    Chennai   2400.0
27             Storage       1.0   6200     Mumbai   6200.0
28              Gaming       2.0   4800      Delhi   9600.0
29               Audio       1.0   6500       Pune   6500.0
30         Electronics       1.0  52000  Hyderabad  52000.0
31               Audio       1.0  14500  Bangalore  14500.0
32         Accessories       2.0   1800    Chennai   3600.0
33         Electronics       1.0   7200     Mumbai   7200.0
34          Networking       1.0   2800      Delhi   2800.0
35     Home Appliances       1.0  11500       Pune  11500.0
36          Smart Home       4.0    850  Hyderabad   3400.0
37         Accessories       2.0   1400  Bangalore   2800.0
38             Cameras       1.0  68000    Chennai  68000.0
39  Camera Accessories       1.0   3500     Mumbai   3500.0
40             Storage       2.0   1600      Delhi   3200.0
41           Wearables       3.0    900       Pune   2700.0
42              Gaming       1.0  32000  Hyderabad  32000.0
43         Electronics       1.0  27500  Bangalore  27500.0
44       Home & Office       1.0   6500    Chennai   6500.0
45               Audio       1.0   9200     Mumbai   9200.0
46             Storage       4.0   1100      Delhi   4400.0
47          Smart Home       1.0   7800       Pune   7800.0
48            Security       2.0   6500  Hyderabad  13000.0
49          Smart Home       1.0   5500  Bangalore   5500.0

In [4]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     50 non-null     object
 1   Order_Date   50 non-null     object
 2   Customer_ID  50 non-null     object
 3   Product      50 non-null     object
 4   Category     50 non-null     object
 5   Quantity     49 non-null     float64
 6   Price        50 non-null     int64
 7   City         50 non-null     object
 8   Revenue      49 non-null     float64
dtypes: float64(2), int64(1), object(6)
memory usage: 3.6+ KB
None

In [6]:
print(data["Revenue"].isna().sum())

1

In [7]:
print(data["Revenue"].isnull().sum())

1

In [9]:
missing_value_per = (data.isna().mean()*100)
print(missing_value_per)

Order_ID       0.0
Order_Date     0.0
Customer_ID    0.0
Product        0.0
Category       0.0
Quantity       2.0
Price          0.0
City           0.0
Revenue        2.0
dtype: float64

In [23]:
data = pd.read_csv("./orders2.csv")
print(data)

   Order_ID  Order_Date Customer_ID                      Product  \
0    ORD051  2026-02-25     CUST051                       Laptop
1    ORD052  2026-02-26     CUST052               Wireless Mouse
2    ORD053  2026-02-27     CUST053                     Keyboard
3    ORD054  2026-02-28     CUST054                      Monitor
4    ORD055  2026-03-01     CUST055                   Headphones
5    ORD056  2026-03-02     CUST056                    USB Cable
6    ORD057  2026-03-03         NaN                       Webcam
7    ORD058  2026-03-04     CUST058                 External SSD
8    ORD059  2026-03-05     CUST059                   Smartphone
9    ORD060  2026-03-06     CUST060                   Power Bank
10   ORD061  2026-03-07     CUST061                 Laptop Stand
11   ORD062  2026-03-08     CUST062          Mechanical Keyboard
12   ORD063  2026-03-09     CUST063            Bluetooth Speaker
13   ORD064  2026-03-10     CUST064                       Tablet
14   ORD065  2026-03-11     CUST065                  Smart Watch
15   ORD066  2026-03-12     CUST066             Wireless Earbuds
16   ORD067  2026-03-13     CUST067                   HDMI Cable
17   ORD068  2026-03-14     CUST068                    Desk Lamp
18   ORD069  2026-03-15     CUST069                 Office Chair
19   ORD070  2026-03-16     CUST070                    Mouse Pad
20   ORD071  2026-03-17     CUST071                   Laptop Bag
21   ORD072  2026-03-18     CUST072                      Printer
22   ORD073  2026-03-19     CUST073                Ink Cartridge
23   ORD074  2026-03-20     CUST074                       Router
24   ORD075  2026-03-21     CUST075              Smartphone Case
25   ORD076  2026-03-22     CUST076             Screen Protector
26   ORD077  2026-03-23     CUST077                Power Adapter
27   ORD078  2026-03-24         NaN          Portable Hard Drive
28   ORD079  2026-03-25     CUST079            Gaming Controller
29   ORD080  2026-03-26     CUST080                   Microphone
30   ORD081  2026-03-27     CUST081                     Smart TV
31   ORD082  2026-03-28     CUST082                     Soundbar
32   ORD083  2026-03-29     CUST083                      USB Hub
33   ORD084  2026-03-30     CUST084              Graphics Tablet
34   ORD085  2026-03-31     CUST085                WiFi Extender
35   ORD086  2026-04-01     CUST086                 Air Purifier
36   ORD087  2026-04-02     CUST087                   Smart Bulb
37   ORD088  2026-04-03     CUST088                  Power Strip
38   ORD089  2026-04-04     CUST089                  DSLR Camera
39   ORD090  2026-04-05     CUST090                Camera Tripod
40   ORD091  2026-04-06     CUST091                  Memory Card
41   ORD092  2026-04-07     CUST092             Smartwatch Strap
42   ORD093  2026-04-08     CUST093                   VR Headset
43   ORD094  2026-04-09     CUST094                    Projector
44   ORD095  2026-04-10     CUST095             Projector Screen
45   ORD096  2026-04-11     CUST096  Noise Cancelling Headphones
46   ORD097  2026-04-12     CUST097              USB Flash Drive
47   ORD098  2026-04-13         NaN               Smart Doorbell
48   ORD099  2026-04-14     CUST099              Security Camera
49   ORD100  2026-04-15     CUST100               Smart Home Hub
50      NaN         NaN         NaN                          NaN

              Category  Quantity    Price       City
0          Electronics       1.0  72000.0  Hyderabad
1          Accessories       2.0   1400.0  Bangalore
2          Accessories       NaN   2800.0    Chennai
3          Electronics       1.0      NaN     Mumbai
4                Audio       2.0   4200.0        NaN
5          Accessories       4.0    700.0       Pune
6          Electronics       1.0   4500.0  Hyderabad
7              Storage       1.0   8500.0  Bangalore
8          Electronics       NaN  45000.0    Chennai
9          Accessories       2.0   2100.0     Mumbai
10                 NaN       1.0   2500.0      Delhi
11         Accessories       1.0   6200.0       Pune
12               Audio       2.0      NaN  Hyderabad
13         Electronics       1.0  31000.0  Bangalore
14           Wearables       1.0   9200.0        NaN
15               Audio       2.0   4800.0     Mumbai
16         Accessories       3.0   1000.0      Delhi
17       Home & Office       NaN   1800.0       Pune
18           Furniture       1.0  13800.0  Hyderabad
19         Accessories       2.0    850.0  Bangalore
20                Bags       1.0      NaN    Chennai
21         Electronics       1.0  16800.0     Mumbai
22    Printer Supplies       NaN   1950.0      Delhi
23          Networking       1.0   4600.0       Pune
24         Accessories       2.0   1100.0        NaN
25         Accessories       3.0    550.0  Hyderabad
26         Accessories       1.0   2600.0  Bangalore
27             Storage       1.0   6800.0    Chennai
28              Gaming       2.0   5200.0     Mumbai
29               Audio       1.0   7200.0      Delhi
30         Electronics       1.0  58000.0       Pune
31               Audio       NaN  15500.0  Hyderabad
32         Accessories       2.0      NaN  Bangalore
33         Electronics       1.0   7800.0    Chennai
34          Networking       1.0   3200.0     Mumbai
35     Home Appliances       NaN  12800.0      Delhi
36          Smart Home       4.0    950.0       Pune
37         Accessories       2.0   1550.0        NaN
38             Cameras       1.0  71000.0  Hyderabad
39  Camera Accessories       1.0   3800.0  Bangalore
40             Storage       2.0   1750.0    Chennai
41           Wearables       3.0      NaN     Mumbai
42              Gaming       1.0  35000.0      Delhi
43         Electronics       NaN  29500.0       Pune
44       Home & Office       1.0   7200.0  Hyderabad
45               Audio       1.0   9800.0        NaN
46             Storage       4.0   1250.0  Bangalore
47          Smart Home       1.0   8200.0    Chennai
48            Security       2.0   6900.0     Mumbai
49          Smart Home       1.0   5900.0      Delhi
50                 NaN       NaN      NaN        NaN

In [24]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     50 non-null     object
 1   Order_Date   50 non-null     object
 2   Customer_ID  47 non-null     object
 3   Product      50 non-null     object
 4   Category     49 non-null     object
 5   Quantity     43 non-null     float64
 6   Price        45 non-null     float64
 7   City         45 non-null     object
dtypes: float64(2), object(6)
memory usage: 3.3+ KB
None

In [25]:
# data = pd.read_csv("orders.csv")

data["Revenue"] = data["Quantity"] * data["Price"]

data.to_csv("orders.csv", index=False)

In [26]:
print(data["Revenue"].isna().sum())

13

In [27]:
print(data["Revenue"].isna().sum())

13

In [28]:
missing_value_per = (data.isna().mean()*100)
print(missing_value_per)

Order_ID        1.960784
Order_Date      1.960784
Customer_ID     7.843137
Product         1.960784
Category        3.921569
Quantity       15.686275
Price          11.764706
City           11.764706
Revenue        25.490196
dtype: float64

In [29]:
rows_with_missing = data[data.isna().any(axis=1)]
print(rows_with_missing)

   Order_ID  Order_Date Customer_ID                      Product  \
2    ORD053  2026-02-27     CUST053                     Keyboard
3    ORD054  2026-02-28     CUST054                      Monitor
4    ORD055  2026-03-01     CUST055                   Headphones
6    ORD057  2026-03-03         NaN                       Webcam
8    ORD059  2026-03-05     CUST059                   Smartphone
10   ORD061  2026-03-07     CUST061                 Laptop Stand
12   ORD063  2026-03-09     CUST063            Bluetooth Speaker
14   ORD065  2026-03-11     CUST065                  Smart Watch
17   ORD068  2026-03-14     CUST068                    Desk Lamp
20   ORD071  2026-03-17     CUST071                   Laptop Bag
22   ORD073  2026-03-19     CUST073                Ink Cartridge
24   ORD075  2026-03-21     CUST075              Smartphone Case
27   ORD078  2026-03-24         NaN          Portable Hard Drive
31   ORD082  2026-03-28     CUST082                     Soundbar
32   ORD083  2026-03-29     CUST083                      USB Hub
35   ORD086  2026-04-01     CUST086                 Air Purifier
37   ORD088  2026-04-03     CUST088                  Power Strip
41   ORD092  2026-04-07     CUST092             Smartwatch Strap
43   ORD094  2026-04-09     CUST094                    Projector
45   ORD096  2026-04-11     CUST096  Noise Cancelling Headphones
47   ORD098  2026-04-13         NaN               Smart Doorbell
50      NaN         NaN         NaN                          NaN

            Category  Quantity    Price       City  Revenue
2        Accessories       NaN   2800.0    Chennai      NaN
3        Electronics       1.0      NaN     Mumbai      NaN
4              Audio       2.0   4200.0        NaN   8400.0
6        Electronics       1.0   4500.0  Hyderabad   4500.0
8        Electronics       NaN  45000.0    Chennai      NaN
10               NaN       1.0   2500.0      Delhi   2500.0
12             Audio       2.0      NaN  Hyderabad      NaN
14         Wearables       1.0   9200.0        NaN   9200.0
17     Home & Office       NaN   1800.0       Pune      NaN
20              Bags       1.0      NaN    Chennai      NaN
22  Printer Supplies       NaN   1950.0      Delhi      NaN
24       Accessories       2.0   1100.0        NaN   2200.0
27           Storage       1.0   6800.0    Chennai   6800.0
31             Audio       NaN  15500.0  Hyderabad      NaN
32       Accessories       2.0      NaN  Bangalore      NaN
35   Home Appliances       NaN  12800.0      Delhi      NaN
37       Accessories       2.0   1550.0        NaN   3100.0
41         Wearables       3.0      NaN     Mumbai      NaN
43       Electronics       NaN  29500.0       Pune      NaN
45             Audio       1.0   9800.0        NaN   9800.0
47        Smart Home       1.0   8200.0    Chennai   8200.0
50               NaN       NaN      NaN        NaN      NaN

In [30]:
blank_rows = data[data.isna().all(axis=1)]
print(blank_rows)

   Order_ID Order_Date Customer_ID Product Category  Quantity  Price City  \
50      NaN        NaN         NaN     NaN      NaN       NaN    NaN  NaN

    Revenue
50      NaN

In [31]:
print(data.dropna(axis=1))

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

In [32]:
print(data)

   Order_ID  Order_Date Customer_ID                      Product  \
0    ORD051  2026-02-25     CUST051                       Laptop
1    ORD052  2026-02-26     CUST052               Wireless Mouse
2    ORD053  2026-02-27     CUST053                     Keyboard
3    ORD054  2026-02-28     CUST054                      Monitor
4    ORD055  2026-03-01     CUST055                   Headphones
5    ORD056  2026-03-02     CUST056                    USB Cable
6    ORD057  2026-03-03         NaN                       Webcam
7    ORD058  2026-03-04     CUST058                 External SSD
8    ORD059  2026-03-05     CUST059                   Smartphone
9    ORD060  2026-03-06     CUST060                   Power Bank
10   ORD061  2026-03-07     CUST061                 Laptop Stand
11   ORD062  2026-03-08     CUST062          Mechanical Keyboard
12   ORD063  2026-03-09     CUST063            Bluetooth Speaker
13   ORD064  2026-03-10     CUST064                       Tablet
14   ORD065  2026-03-11     CUST065                  Smart Watch
15   ORD066  2026-03-12     CUST066             Wireless Earbuds
16   ORD067  2026-03-13     CUST067                   HDMI Cable
17   ORD068  2026-03-14     CUST068                    Desk Lamp
18   ORD069  2026-03-15     CUST069                 Office Chair
19   ORD070  2026-03-16     CUST070                    Mouse Pad
20   ORD071  2026-03-17     CUST071                   Laptop Bag
21   ORD072  2026-03-18     CUST072                      Printer
22   ORD073  2026-03-19     CUST073                Ink Cartridge
23   ORD074  2026-03-20     CUST074                       Router
24   ORD075  2026-03-21     CUST075              Smartphone Case
25   ORD076  2026-03-22     CUST076             Screen Protector
26   ORD077  2026-03-23     CUST077                Power Adapter
27   ORD078  2026-03-24         NaN          Portable Hard Drive
28   ORD079  2026-03-25     CUST079            Gaming Controller
29   ORD080  2026-03-26     CUST080                   Microphone
30   ORD081  2026-03-27     CUST081                     Smart TV
31   ORD082  2026-03-28     CUST082                     Soundbar
32   ORD083  2026-03-29     CUST083                      USB Hub
33   ORD084  2026-03-30     CUST084              Graphics Tablet
34   ORD085  2026-03-31     CUST085                WiFi Extender
35   ORD086  2026-04-01     CUST086                 Air Purifier
36   ORD087  2026-04-02     CUST087                   Smart Bulb
37   ORD088  2026-04-03     CUST088                  Power Strip
38   ORD089  2026-04-04     CUST089                  DSLR Camera
39   ORD090  2026-04-05     CUST090                Camera Tripod
40   ORD091  2026-04-06     CUST091                  Memory Card
41   ORD092  2026-04-07     CUST092             Smartwatch Strap
42   ORD093  2026-04-08     CUST093                   VR Headset
43   ORD094  2026-04-09     CUST094                    Projector
44   ORD095  2026-04-10     CUST095             Projector Screen
45   ORD096  2026-04-11     CUST096  Noise Cancelling Headphones
46   ORD097  2026-04-12     CUST097              USB Flash Drive
47   ORD098  2026-04-13         NaN               Smart Doorbell
48   ORD099  2026-04-14     CUST099              Security Camera
49   ORD100  2026-04-15     CUST100               Smart Home Hub
50      NaN         NaN         NaN                          NaN

              Category  Quantity    Price       City  Revenue
0          Electronics       1.0  72000.0  Hyderabad  72000.0
1          Accessories       2.0   1400.0  Bangalore   2800.0
2          Accessories       NaN   2800.0    Chennai      NaN
3          Electronics       1.0      NaN     Mumbai      NaN
4                Audio       2.0   4200.0        NaN   8400.0
5          Accessories       4.0    700.0       Pune   2800.0
6          Electronics       1.0   4500.0  Hyderabad   4500.0
7              Storage       1.0   8500.0  Bangalore   8500.0
8          Electronics       NaN  45000.0    Chennai      NaN
9          Accessories       2.0   2100.0     Mumbai   4200.0
10                 NaN       1.0   2500.0      Delhi   2500.0
11         Accessories       1.0   6200.0       Pune   6200.0
12               Audio       2.0      NaN  Hyderabad      NaN
13         Electronics       1.0  31000.0  Bangalore  31000.0
14           Wearables       1.0   9200.0        NaN   9200.0
15               Audio       2.0   4800.0     Mumbai   9600.0
16         Accessories       3.0   1000.0      Delhi   3000.0
17       Home & Office       NaN   1800.0       Pune      NaN
18           Furniture       1.0  13800.0  Hyderabad  13800.0
19         Accessories       2.0    850.0  Bangalore   1700.0
20                Bags       1.0      NaN    Chennai      NaN
21         Electronics       1.0  16800.0     Mumbai  16800.0
22    Printer Supplies       NaN   1950.0      Delhi      NaN
23          Networking       1.0   4600.0       Pune   4600.0
24         Accessories       2.0   1100.0        NaN   2200.0
25         Accessories       3.0    550.0  Hyderabad   1650.0
26         Accessories       1.0   2600.0  Bangalore   2600.0
27             Storage       1.0   6800.0    Chennai   6800.0
28              Gaming       2.0   5200.0     Mumbai  10400.0
29               Audio       1.0   7200.0      Delhi   7200.0
30         Electronics       1.0  58000.0       Pune  58000.0
31               Audio       NaN  15500.0  Hyderabad      NaN
32         Accessories       2.0      NaN  Bangalore      NaN
33         Electronics       1.0   7800.0    Chennai   7800.0
34          Networking       1.0   3200.0     Mumbai   3200.0
35     Home Appliances       NaN  12800.0      Delhi      NaN
36          Smart Home       4.0    950.0       Pune   3800.0
37         Accessories       2.0   1550.0        NaN   3100.0
38             Cameras       1.0  71000.0  Hyderabad  71000.0
39  Camera Accessories       1.0   3800.0  Bangalore   3800.0
40             Storage       2.0   1750.0    Chennai   3500.0
41           Wearables       3.0      NaN     Mumbai      NaN
42              Gaming       1.0  35000.0      Delhi  35000.0
43         Electronics       NaN  29500.0       Pune      NaN
44       Home & Office       1.0   7200.0  Hyderabad   7200.0
45               Audio       1.0   9800.0        NaN   9800.0
46             Storage       4.0   1250.0  Bangalore   5000.0
47          Smart Home       1.0   8200.0    Chennai   8200.0
48            Security       2.0   6900.0     Mumbai  13800.0
49          Smart Home       1.0   5900.0      Delhi   5900.0
50                 NaN       NaN      NaN        NaN      NaN

In [34]:
print(data.dropna(how="all"))

   Order_ID  Order_Date Customer_ID                      Product  \
0    ORD051  2026-02-25     CUST051                       Laptop
1    ORD052  2026-02-26     CUST052               Wireless Mouse
2    ORD053  2026-02-27     CUST053                     Keyboard
3    ORD054  2026-02-28     CUST054                      Monitor
4    ORD055  2026-03-01     CUST055                   Headphones
5    ORD056  2026-03-02     CUST056                    USB Cable
6    ORD057  2026-03-03         NaN                       Webcam
7    ORD058  2026-03-04     CUST058                 External SSD
8    ORD059  2026-03-05     CUST059                   Smartphone
9    ORD060  2026-03-06     CUST060                   Power Bank
10   ORD061  2026-03-07     CUST061                 Laptop Stand
11   ORD062  2026-03-08     CUST062          Mechanical Keyboard
12   ORD063  2026-03-09     CUST063            Bluetooth Speaker
13   ORD064  2026-03-10     CUST064                       Tablet
14   ORD065  2026-03-11     CUST065                  Smart Watch
15   ORD066  2026-03-12     CUST066             Wireless Earbuds
16   ORD067  2026-03-13     CUST067                   HDMI Cable
17   ORD068  2026-03-14     CUST068                    Desk Lamp
18   ORD069  2026-03-15     CUST069                 Office Chair
19   ORD070  2026-03-16     CUST070                    Mouse Pad
20   ORD071  2026-03-17     CUST071                   Laptop Bag
21   ORD072  2026-03-18     CUST072                      Printer
22   ORD073  2026-03-19     CUST073                Ink Cartridge
23   ORD074  2026-03-20     CUST074                       Router
24   ORD075  2026-03-21     CUST075              Smartphone Case
25   ORD076  2026-03-22     CUST076             Screen Protector
26   ORD077  2026-03-23     CUST077                Power Adapter
27   ORD078  2026-03-24         NaN          Portable Hard Drive
28   ORD079  2026-03-25     CUST079            Gaming Controller
29   ORD080  2026-03-26     CUST080                   Microphone
30   ORD081  2026-03-27     CUST081                     Smart TV
31   ORD082  2026-03-28     CUST082                     Soundbar
32   ORD083  2026-03-29     CUST083                      USB Hub
33   ORD084  2026-03-30     CUST084              Graphics Tablet
34   ORD085  2026-03-31     CUST085                WiFi Extender
35   ORD086  2026-04-01     CUST086                 Air Purifier
36   ORD087  2026-04-02     CUST087                   Smart Bulb
37   ORD088  2026-04-03     CUST088                  Power Strip
38   ORD089  2026-04-04     CUST089                  DSLR Camera
39   ORD090  2026-04-05     CUST090                Camera Tripod
40   ORD091  2026-04-06     CUST091                  Memory Card
41   ORD092  2026-04-07     CUST092             Smartwatch Strap
42   ORD093  2026-04-08     CUST093                   VR Headset
43   ORD094  2026-04-09     CUST094                    Projector
44   ORD095  2026-04-10     CUST095             Projector Screen
45   ORD096  2026-04-11     CUST096  Noise Cancelling Headphones
46   ORD097  2026-04-12     CUST097              USB Flash Drive
47   ORD098  2026-04-13         NaN               Smart Doorbell
48   ORD099  2026-04-14     CUST099              Security Camera
49   ORD100  2026-04-15     CUST100               Smart Home Hub

              Category  Quantity    Price       City  Revenue
0          Electronics       1.0  72000.0  Hyderabad  72000.0
1          Accessories       2.0   1400.0  Bangalore   2800.0
2          Accessories       NaN   2800.0    Chennai      NaN
3          Electronics       1.0      NaN     Mumbai      NaN
4                Audio       2.0   4200.0        NaN   8400.0
5          Accessories       4.0    700.0       Pune   2800.0
6          Electronics       1.0   4500.0  Hyderabad   4500.0
7              Storage       1.0   8500.0  Bangalore   8500.0
8          Electronics       NaN  45000.0    Chennai      NaN
9          Accessories       2.0   2100.0     Mumbai   4200.0
10                 NaN       1.0   2500.0      Delhi   2500.0
11         Accessories       1.0   6200.0       Pune   6200.0
12               Audio       2.0      NaN  Hyderabad      NaN
13         Electronics       1.0  31000.0  Bangalore  31000.0
14           Wearables       1.0   9200.0        NaN   9200.0
15               Audio       2.0   4800.0     Mumbai   9600.0
16         Accessories       3.0   1000.0      Delhi   3000.0
17       Home & Office       NaN   1800.0       Pune      NaN
18           Furniture       1.0  13800.0  Hyderabad  13800.0
19         Accessories       2.0    850.0  Bangalore   1700.0
20                Bags       1.0      NaN    Chennai      NaN
21         Electronics       1.0  16800.0     Mumbai  16800.0
22    Printer Supplies       NaN   1950.0      Delhi      NaN
23          Networking       1.0   4600.0       Pune   4600.0
24         Accessories       2.0   1100.0        NaN   2200.0
25         Accessories       3.0    550.0  Hyderabad   1650.0
26         Accessories       1.0   2600.0  Bangalore   2600.0
27             Storage       1.0   6800.0    Chennai   6800.0
28              Gaming       2.0   5200.0     Mumbai  10400.0
29               Audio       1.0   7200.0      Delhi   7200.0
30         Electronics       1.0  58000.0       Pune  58000.0
31               Audio       NaN  15500.0  Hyderabad      NaN
32         Accessories       2.0      NaN  Bangalore      NaN
33         Electronics       1.0   7800.0    Chennai   7800.0
34          Networking       1.0   3200.0     Mumbai   3200.0
35     Home Appliances       NaN  12800.0      Delhi      NaN
36          Smart Home       4.0    950.0       Pune   3800.0
37         Accessories       2.0   1550.0        NaN   3100.0
38             Cameras       1.0  71000.0  Hyderabad  71000.0
39  Camera Accessories       1.0   3800.0  Bangalore   3800.0
40             Storage       2.0   1750.0    Chennai   3500.0
41           Wearables       3.0      NaN     Mumbai      NaN
42              Gaming       1.0  35000.0      Delhi  35000.0
43         Electronics       NaN  29500.0       Pune      NaN
44       Home & Office       1.0   7200.0  Hyderabad   7200.0
45               Audio       1.0   9800.0        NaN   9800.0
46             Storage       4.0   1250.0  Bangalore   5000.0
47          Smart Home       1.0   8200.0    Chennai   8200.0
48            Security       2.0   6900.0     Mumbai  13800.0
49          Smart Home       1.0   5900.0      Delhi   5900.0

In [33]:
print(data.dropna(how="any"))

   Order_ID  Order_Date Customer_ID              Product            Category  \
0    ORD051  2026-02-25     CUST051               Laptop         Electronics
1    ORD052  2026-02-26     CUST052       Wireless Mouse         Accessories
5    ORD056  2026-03-02     CUST056            USB Cable         Accessories
7    ORD058  2026-03-04     CUST058         External SSD             Storage
9    ORD060  2026-03-06     CUST060           Power Bank         Accessories
11   ORD062  2026-03-08     CUST062  Mechanical Keyboard         Accessories
13   ORD064  2026-03-10     CUST064               Tablet         Electronics
15   ORD066  2026-03-12     CUST066     Wireless Earbuds               Audio
16   ORD067  2026-03-13     CUST067           HDMI Cable         Accessories
18   ORD069  2026-03-15     CUST069         Office Chair           Furniture
19   ORD070  2026-03-16     CUST070            Mouse Pad         Accessories
21   ORD072  2026-03-18     CUST072              Printer         Electronics
23   ORD074  2026-03-20     CUST074               Router          Networking
25   ORD076  2026-03-22     CUST076     Screen Protector         Accessories
26   ORD077  2026-03-23     CUST077        Power Adapter         Accessories
28   ORD079  2026-03-25     CUST079    Gaming Controller              Gaming
29   ORD080  2026-03-26     CUST080           Microphone               Audio
30   ORD081  2026-03-27     CUST081             Smart TV         Electronics
33   ORD084  2026-03-30     CUST084      Graphics Tablet         Electronics
34   ORD085  2026-03-31     CUST085        WiFi Extender          Networking
36   ORD087  2026-04-02     CUST087           Smart Bulb          Smart Home
38   ORD089  2026-04-04     CUST089          DSLR Camera             Cameras
39   ORD090  2026-04-05     CUST090        Camera Tripod  Camera Accessories
40   ORD091  2026-04-06     CUST091          Memory Card             Storage
42   ORD093  2026-04-08     CUST093           VR Headset              Gaming
44   ORD095  2026-04-10     CUST095     Projector Screen       Home & Office
46   ORD097  2026-04-12     CUST097      USB Flash Drive             Storage
48   ORD099  2026-04-14     CUST099      Security Camera            Security
49   ORD100  2026-04-15     CUST100       Smart Home Hub          Smart Home

    Quantity    Price       City  Revenue
0        1.0  72000.0  Hyderabad  72000.0
1        2.0   1400.0  Bangalore   2800.0
5        4.0    700.0       Pune   2800.0
7        1.0   8500.0  Bangalore   8500.0
9        2.0   2100.0     Mumbai   4200.0
11       1.0   6200.0       Pune   6200.0
13       1.0  31000.0  Bangalore  31000.0
15       2.0   4800.0     Mumbai   9600.0
16       3.0   1000.0      Delhi   3000.0
18       1.0  13800.0  Hyderabad  13800.0
19       2.0    850.0  Bangalore   1700.0
21       1.0  16800.0     Mumbai  16800.0
23       1.0   4600.0       Pune   4600.0
25       3.0    550.0  Hyderabad   1650.0
26       1.0   2600.0  Bangalore   2600.0
28       2.0   5200.0     Mumbai  10400.0
29       1.0   7200.0      Delhi   7200.0
30       1.0  58000.0       Pune  58000.0
33       1.0   7800.0    Chennai   7800.0
34       1.0   3200.0     Mumbai   3200.0
36       4.0    950.0       Pune   3800.0
38       1.0  71000.0  Hyderabad  71000.0
39       1.0   3800.0  Bangalore   3800.0
40       2.0   1750.0    Chennai   3500.0
42       1.0  35000.0      Delhi  35000.0
44       1.0   7200.0  Hyderabad   7200.0
46       4.0   1250.0  Bangalore   5000.0
48       2.0   6900.0     Mumbai  13800.0
49       1.0   5900.0      Delhi   5900.0

In [37]:
data["empty"] = None
# print(data)
print(data.dropna(how="any"))

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Product, Category, Quantity, Price, City, Revenue, empty]
Index: []

In [38]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     50 non-null     object
 1   Order_Date   50 non-null     object
 2   Customer_ID  47 non-null     object
 3   Product      50 non-null     object
 4   Category     49 non-null     object
 5   Quantity     43 non-null     float64
 6   Price        45 non-null     float64
 7   City         45 non-null     object
 8   Revenue      38 non-null     float64
 9   empty        0 non-null      object
dtypes: float64(3), object(7)
memory usage: 4.1+ KB
None

In [41]:
print(data.dropna(axis=1,thresh=40))
# print(data.info())
#here since the revenuce column has only 38 values, 
# the threshold is minimum 40 so it removes the revenue column

   Order_ID  Order_Date Customer_ID                      Product  \
0    ORD051  2026-02-25     CUST051                       Laptop
1    ORD052  2026-02-26     CUST052               Wireless Mouse
2    ORD053  2026-02-27     CUST053                     Keyboard
3    ORD054  2026-02-28     CUST054                      Monitor
4    ORD055  2026-03-01     CUST055                   Headphones
5    ORD056  2026-03-02     CUST056                    USB Cable
6    ORD057  2026-03-03         NaN                       Webcam
7    ORD058  2026-03-04     CUST058                 External SSD
8    ORD059  2026-03-05     CUST059                   Smartphone
9    ORD060  2026-03-06     CUST060                   Power Bank
10   ORD061  2026-03-07     CUST061                 Laptop Stand
11   ORD062  2026-03-08     CUST062          Mechanical Keyboard
12   ORD063  2026-03-09     CUST063            Bluetooth Speaker
13   ORD064  2026-03-10     CUST064                       Tablet
14   ORD065  2026-03-11     CUST065                  Smart Watch
15   ORD066  2026-03-12     CUST066             Wireless Earbuds
16   ORD067  2026-03-13     CUST067                   HDMI Cable
17   ORD068  2026-03-14     CUST068                    Desk Lamp
18   ORD069  2026-03-15     CUST069                 Office Chair
19   ORD070  2026-03-16     CUST070                    Mouse Pad
20   ORD071  2026-03-17     CUST071                   Laptop Bag
21   ORD072  2026-03-18     CUST072                      Printer
22   ORD073  2026-03-19     CUST073                Ink Cartridge
23   ORD074  2026-03-20     CUST074                       Router
24   ORD075  2026-03-21     CUST075              Smartphone Case
25   ORD076  2026-03-22     CUST076             Screen Protector
26   ORD077  2026-03-23     CUST077                Power Adapter
27   ORD078  2026-03-24         NaN          Portable Hard Drive
28   ORD079  2026-03-25     CUST079            Gaming Controller
29   ORD080  2026-03-26     CUST080                   Microphone
30   ORD081  2026-03-27     CUST081                     Smart TV
31   ORD082  2026-03-28     CUST082                     Soundbar
32   ORD083  2026-03-29     CUST083                      USB Hub
33   ORD084  2026-03-30     CUST084              Graphics Tablet
34   ORD085  2026-03-31     CUST085                WiFi Extender
35   ORD086  2026-04-01     CUST086                 Air Purifier
36   ORD087  2026-04-02     CUST087                   Smart Bulb
37   ORD088  2026-04-03     CUST088                  Power Strip
38   ORD089  2026-04-04     CUST089                  DSLR Camera
39   ORD090  2026-04-05     CUST090                Camera Tripod
40   ORD091  2026-04-06     CUST091                  Memory Card
41   ORD092  2026-04-07     CUST092             Smartwatch Strap
42   ORD093  2026-04-08     CUST093                   VR Headset
43   ORD094  2026-04-09     CUST094                    Projector
44   ORD095  2026-04-10     CUST095             Projector Screen
45   ORD096  2026-04-11     CUST096  Noise Cancelling Headphones
46   ORD097  2026-04-12     CUST097              USB Flash Drive
47   ORD098  2026-04-13         NaN               Smart Doorbell
48   ORD099  2026-04-14     CUST099              Security Camera
49   ORD100  2026-04-15     CUST100               Smart Home Hub
50      NaN         NaN         NaN                          NaN

              Category  Quantity    Price       City
0          Electronics       1.0  72000.0  Hyderabad
1          Accessories       2.0   1400.0  Bangalore
2          Accessories       NaN   2800.0    Chennai
3          Electronics       1.0      NaN     Mumbai
4                Audio       2.0   4200.0        NaN
5          Accessories       4.0    700.0       Pune
6          Electronics       1.0   4500.0  Hyderabad
7              Storage       1.0   8500.0  Bangalore
8          Electronics       NaN  45000.0    Chennai
9          Accessories       2.0   2100.0     Mumbai
10                 NaN       1.0   2500.0      Delhi
11         Accessories       1.0   6200.0       Pune
12               Audio       2.0      NaN  Hyderabad
13         Electronics       1.0  31000.0  Bangalore
14           Wearables       1.0   9200.0        NaN
15               Audio       2.0   4800.0     Mumbai
16         Accessories       3.0   1000.0      Delhi
17       Home & Office       NaN   1800.0       Pune
18           Furniture       1.0  13800.0  Hyderabad
19         Accessories       2.0    850.0  Bangalore
20                Bags       1.0      NaN    Chennai
21         Electronics       1.0  16800.0     Mumbai
22    Printer Supplies       NaN   1950.0      Delhi
23          Networking       1.0   4600.0       Pune
24         Accessories       2.0   1100.0        NaN
25         Accessories       3.0    550.0  Hyderabad
26         Accessories       1.0   2600.0  Bangalore
27             Storage       1.0   6800.0    Chennai
28              Gaming       2.0   5200.0     Mumbai
29               Audio       1.0   7200.0      Delhi
30         Electronics       1.0  58000.0       Pune
31               Audio       NaN  15500.0  Hyderabad
32         Accessories       2.0      NaN  Bangalore
33         Electronics       1.0   7800.0    Chennai
34          Networking       1.0   3200.0     Mumbai
35     Home Appliances       NaN  12800.0      Delhi
36          Smart Home       4.0    950.0       Pune
37         Accessories       2.0   1550.0        NaN
38             Cameras       1.0  71000.0  Hyderabad
39  Camera Accessories       1.0   3800.0  Bangalore
40             Storage       2.0   1750.0    Chennai
41           Wearables       3.0      NaN     Mumbai
42              Gaming       1.0  35000.0      Delhi
43         Electronics       NaN  29500.0       Pune
44       Home & Office       1.0   7200.0  Hyderabad
45               Audio       1.0   9800.0        NaN
46             Storage       4.0   1250.0  Bangalore
47          Smart Home       1.0   8200.0    Chennai
48            Security       2.0   6900.0     Mumbai
49          Smart Home       1.0   5900.0      Delhi
50                 NaN       NaN      NaN        NaN

In [ ]:
data["Revenue"] = data["Revenue"].fillna(data["Quantity"] * data["Price"])
# print(data[["Quantity", "Price", "Revenue"]].head())

   Quantity    Price  Revenue
0       1.0  72000.0  72000.0
1       2.0   1400.0   2800.0
2       NaN   2800.0      NaN
3       1.0      NaN      NaN
4       2.0   4200.0   8400.0

In [44]:
print(data.fillna(data["Revenue"].mean()))

        Order_ID    Order_Date   Customer_ID                      Product  \
0         ORD051    2026-02-25       CUST051                       Laptop
1         ORD052    2026-02-26       CUST052               Wireless Mouse
2         ORD053    2026-02-27       CUST053                     Keyboard
3         ORD054    2026-02-28       CUST054                      Monitor
4         ORD055    2026-03-01       CUST055                   Headphones
5         ORD056    2026-03-02       CUST056                    USB Cable
6         ORD057    2026-03-03  12409.210526                       Webcam
7         ORD058    2026-03-04       CUST058                 External SSD
8         ORD059    2026-03-05       CUST059                   Smartphone
9         ORD060    2026-03-06       CUST060                   Power Bank
10        ORD061    2026-03-07       CUST061                 Laptop Stand
11        ORD062    2026-03-08       CUST062          Mechanical Keyboard
12        ORD063    2026-03-09       CUST063            Bluetooth Speaker
13        ORD064    2026-03-10       CUST064                       Tablet
14        ORD065    2026-03-11       CUST065                  Smart Watch
15        ORD066    2026-03-12       CUST066             Wireless Earbuds
16        ORD067    2026-03-13       CUST067                   HDMI Cable
17        ORD068    2026-03-14       CUST068                    Desk Lamp
18        ORD069    2026-03-15       CUST069                 Office Chair
19        ORD070    2026-03-16       CUST070                    Mouse Pad
20        ORD071    2026-03-17       CUST071                   Laptop Bag
21        ORD072    2026-03-18       CUST072                      Printer
22        ORD073    2026-03-19       CUST073                Ink Cartridge
23        ORD074    2026-03-20       CUST074                       Router
24        ORD075    2026-03-21       CUST075              Smartphone Case
25        ORD076    2026-03-22       CUST076             Screen Protector
26        ORD077    2026-03-23       CUST077                Power Adapter
27        ORD078    2026-03-24  12409.210526          Portable Hard Drive
28        ORD079    2026-03-25       CUST079            Gaming Controller
29        ORD080    2026-03-26       CUST080                   Microphone
30        ORD081    2026-03-27       CUST081                     Smart TV
31        ORD082    2026-03-28       CUST082                     Soundbar
32        ORD083    2026-03-29       CUST083                      USB Hub
33        ORD084    2026-03-30       CUST084              Graphics Tablet
34        ORD085    2026-03-31       CUST085                WiFi Extender
35        ORD086    2026-04-01       CUST086                 Air Purifier
36        ORD087    2026-04-02       CUST087                   Smart Bulb
37        ORD088    2026-04-03       CUST088                  Power Strip
38        ORD089    2026-04-04       CUST089                  DSLR Camera
39        ORD090    2026-04-05       CUST090                Camera Tripod
40        ORD091    2026-04-06       CUST091                  Memory Card
41        ORD092    2026-04-07       CUST092             Smartwatch Strap
42        ORD093    2026-04-08       CUST093                   VR Headset
43        ORD094    2026-04-09       CUST094                    Projector
44        ORD095    2026-04-10       CUST095             Projector Screen
45        ORD096    2026-04-11       CUST096  Noise Cancelling Headphones
46        ORD097    2026-04-12       CUST097              USB Flash Drive
47        ORD098    2026-04-13  12409.210526               Smart Doorbell
48        ORD099    2026-04-14       CUST099              Security Camera
49        ORD100    2026-04-15       CUST100               Smart Home Hub
50  12409.210526  12409.210526  12409.210526                 12409.210526

              Category      Quantity         Price          City  \
0          Electronics      1.000000  72000.000000     Hyderabad
1          Accessories      2.000000   1400.000000     Bangalore
2          Accessories  12409.210526   2800.000000       Chennai
3          Electronics      1.000000  12409.210526        Mumbai
4                Audio      2.000000   4200.000000  12409.210526
5          Accessories      4.000000    700.000000          Pune
6          Electronics      1.000000   4500.000000     Hyderabad
7              Storage      1.000000   8500.000000     Bangalore
8          Electronics  12409.210526  45000.000000       Chennai
9          Accessories      2.000000   2100.000000        Mumbai
10        12409.210526      1.000000   2500.000000         Delhi
11         Accessories      1.000000   6200.000000          Pune
12               Audio      2.000000  12409.210526     Hyderabad
13         Electronics      1.000000  31000.000000     Bangalore
14           Wearables      1.000000   9200.000000  12409.210526
15               Audio      2.000000   4800.000000        Mumbai
16         Accessories      3.000000   1000.000000         Delhi
17       Home & Office  12409.210526   1800.000000          Pune
18           Furniture      1.000000  13800.000000     Hyderabad
19         Accessories      2.000000    850.000000     Bangalore
20                Bags      1.000000  12409.210526       Chennai
21         Electronics      1.000000  16800.000000        Mumbai
22    Printer Supplies  12409.210526   1950.000000         Delhi
23          Networking      1.000000   4600.000000          Pune
24         Accessories      2.000000   1100.000000  12409.210526
25         Accessories      3.000000    550.000000     Hyderabad
26         Accessories      1.000000   2600.000000     Bangalore
27             Storage      1.000000   6800.000000       Chennai
28              Gaming      2.000000   5200.000000        Mumbai
29               Audio      1.000000   7200.000000         Delhi
30         Electronics      1.000000  58000.000000          Pune
31               Audio  12409.210526  15500.000000     Hyderabad
32         Accessories      2.000000  12409.210526     Bangalore
33         Electronics      1.000000   7800.000000       Chennai
34          Networking      1.000000   3200.000000        Mumbai
35     Home Appliances  12409.210526  12800.000000         Delhi
36          Smart Home      4.000000    950.000000          Pune
37         Accessories      2.000000   1550.000000  12409.210526
38             Cameras      1.000000  71000.000000     Hyderabad
39  Camera Accessories      1.000000   3800.000000     Bangalore
40             Storage      2.000000   1750.000000       Chennai
41           Wearables      3.000000  12409.210526        Mumbai
42              Gaming      1.000000  35000.000000         Delhi
43         Electronics  12409.210526  29500.000000          Pune
44       Home & Office      1.000000   7200.000000     Hyderabad
45               Audio      1.000000   9800.000000  12409.210526
46             Storage      4.000000   1250.000000     Bangalore
47          Smart Home      1.000000   8200.000000       Chennai
48            Security      2.000000   6900.000000        Mumbai
49          Smart Home      1.000000   5900.000000         Delhi
50        12409.210526  12409.210526  12409.210526  12409.210526

         Revenue         empty
0   72000.000000  12409.210526
1    2800.000000  12409.210526
2   12409.210526  12409.210526
3   12409.210526  12409.210526
4    8400.000000  12409.210526
5    2800.000000  12409.210526
6    4500.000000  12409.210526
7    8500.000000  12409.210526
8   12409.210526  12409.210526
9    4200.000000  12409.210526
10   2500.000000  12409.210526
11   6200.000000  12409.210526
12  12409.210526  12409.210526
13  31000.000000  12409.210526
14   9200.000000  12409.210526
15   9600.000000  12409.210526
16   3000.000000  12409.210526
17  12409.210526  12409.210526
18  13800.000000  12409.210526
19   1700.000000  12409.210526
20  12409.210526  12409.210526
21  16800.000000  12409.210526
22  12409.210526  12409.210526
23   4600.000000  12409.210526
24   2200.000000  12409.210526
25   1650.000000  12409.210526
26   2600.000000  12409.210526
27   6800.000000  12409.210526
28  10400.000000  12409.210526
29   7200.000000  12409.210526
30  58000.000000  12409.210526
31  12409.210526  12409.210526
32  12409.210526  12409.210526
33   7800.000000  12409.210526
34   3200.000000  12409.210526
35  12409.210526  12409.210526
36   3800.000000  12409.210526
37   3100.000000  12409.210526
38  71000.000000  12409.210526
39   3800.000000  12409.210526
40   3500.000000  12409.210526
41  12409.210526  12409.210526
42  35000.000000  12409.210526
43  12409.210526  12409.210526
44   7200.000000  12409.210526
45   9800.000000  12409.210526
46   5000.000000  12409.210526
47   8200.000000  12409.210526
48  13800.000000  12409.210526
49   5900.000000  12409.210526
50  12409.210526  12409.210526

/var/folders/fk/sm7t5yw17_b52m55y9rfvlr80000gn/T/ipykernel_7718/4205402451.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  print(data.fillna(data["Revenue"].mean()))

In [47]:
data = data.drop(columns=["empty"])

data.to_csv("./orders2.csv", index=False)

KeyError: "['empty'] not found in axis"

In [46]:
print(data.columns)

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product', 'Category',
       'Quantity', 'Price', 'City', 'Revenue'],
      dtype='object')

In [48]:
data.to_csv("./orders2.csv", index=False)

In [49]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     50 non-null     object
 1   Order_Date   50 non-null     object
 2   Customer_ID  47 non-null     object
 3   Product      50 non-null     object
 4   Category     49 non-null     object
 5   Quantity     43 non-null     float64
 6   Price        45 non-null     float64
 7   City         45 non-null     object
 8   Revenue      38 non-null     float64
dtypes: float64(3), object(6)
memory usage: 3.7+ KB
None

In [50]:
print(data["Price"].fillna(data["Price"].median()))

0     72000.0
1      1400.0
2      2800.0
3      5200.0
4      4200.0
5       700.0
6      4500.0
7      8500.0
8     45000.0
9      2100.0
10     2500.0
11     6200.0
12     5200.0
13    31000.0
14     9200.0
15     4800.0
16     1000.0
17     1800.0
18    13800.0
19      850.0
20     5200.0
21    16800.0
22     1950.0
23     4600.0
24     1100.0
25      550.0
26     2600.0
27     6800.0
28     5200.0
29     7200.0
30    58000.0
31    15500.0
32     5200.0
33     7800.0
34     3200.0
35    12800.0
36      950.0
37     1550.0
38    71000.0
39     3800.0
40     1750.0
41     5200.0
42    35000.0
43    29500.0
44     7200.0
45     9800.0
46     1250.0
47     8200.0
48     6900.0
49     5900.0
50     5200.0
Name: Price, dtype: float64

In [51]:
print(data["Price"].fillna(data["Price"].mean()))

0     72000.000000
1      1400.000000
2      2800.000000
3     11983.333333
4      4200.000000
5       700.000000
6      4500.000000
7      8500.000000
8     45000.000000
9      2100.000000
10     2500.000000
11     6200.000000
12    11983.333333
13    31000.000000
14     9200.000000
15     4800.000000
16     1000.000000
17     1800.000000
18    13800.000000
19      850.000000
20    11983.333333
21    16800.000000
22     1950.000000
23     4600.000000
24     1100.000000
25      550.000000
26     2600.000000
27     6800.000000
28     5200.000000
29     7200.000000
30    58000.000000
31    15500.000000
32    11983.333333
33     7800.000000
34     3200.000000
35    12800.000000
36      950.000000
37     1550.000000
38    71000.000000
39     3800.000000
40     1750.000000
41    11983.333333
42    35000.000000
43    29500.000000
44     7200.000000
45     9800.000000
46     1250.000000
47     8200.000000
48     6900.000000
49     5900.000000
50    11983.333333
Name: Price, dtype: float64

In [52]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     50 non-null     object
 1   Order_Date   50 non-null     object
 2   Customer_ID  47 non-null     object
 3   Product      50 non-null     object
 4   Category     49 non-null     object
 5   Quantity     43 non-null     float64
 6   Price        45 non-null     float64
 7   City         45 non-null     object
 8   Revenue      38 non-null     float64
dtypes: float64(3), object(6)
memory usage: 3.7+ KB
None

In [55]:
print(data["Category"].mode())

0    Accessories
Name: Category, dtype: object

In [56]:
print(data["Category"].mode()[0])

Accessories

In [57]:
print(data["Category"].fillna(data["Category"].mode()[0]))

0            Electronics
1            Accessories
2            Accessories
3            Electronics
4                  Audio
5            Accessories
6            Electronics
7                Storage
8            Electronics
9            Accessories
10           Accessories
11           Accessories
12                 Audio
13           Electronics
14             Wearables
15                 Audio
16           Accessories
17         Home & Office
18             Furniture
19           Accessories
20                  Bags
21           Electronics
22      Printer Supplies
23            Networking
24           Accessories
25           Accessories
26           Accessories
27               Storage
28                Gaming
29                 Audio
30           Electronics
31                 Audio
32           Accessories
33           Electronics
34            Networking
35       Home Appliances
36            Smart Home
37           Accessories
38               Cameras
39    Camera Accessories
40               Storage
41             Wearables
42                Gaming
43           Electronics
44         Home & Office
45                 Audio
46               Storage
47            Smart Home
48              Security
49            Smart Home
50           Accessories
Name: Category, dtype: object

In [1]:
import pandas as pd

In [ ]:
dates = pd.to_datetime("20-12-2022, 22-11-2002")
print(dates)

2022-12-20 22:00:00-20:02

In [6]:
print(type(dates))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [7]:
data = pd.read_csv("./orders.csv")

In [8]:
data.head()

,Order_ID,Order_Date,Customer_ID,Product,Category,Quantity,Price,City,Revenue
0,ORD051,2026-02-25,CUST051,Laptop,Electronics,1.0,72000.0,Hyderabad,72000.0
1,ORD052,2026-02-26,CUST052,Wireless Mouse,Accessories,2.0,1400.0,Bangalore,2800.0
2,ORD053,2026-02-27,CUST053,Keyboard,Accessories,NaN,2800.0,Chennai,NaN
3,ORD054,2026-02-28,CUST054,Monitor,Electronics,1.0,NaN,Mumbai,NaN
4,ORD055,2026-03-01,CUST055,Headphones,Audio,2.0,4200.0,NaN,8400.0

In [14]:
data["Order_Date"] = pd.to_datetime(
    data["Order_Date"],
    format="%d-%m-%Y"
)
print(data["Order_Date"])

0    2026-02-25
1    2026-02-26
2    2026-02-27
3    2026-02-28
4    2026-03-01
5    2026-03-02
6    2026-03-03
7    2026-03-04
8    2026-03-05
9    2026-03-06
10   2026-03-07
11   2026-03-08
12   2026-03-09
13   2026-03-10
14   2026-03-11
15   2026-03-12
16   2026-03-13
17   2026-03-14
18   2026-03-15
19   2026-03-16
20   2026-03-17
21   2026-03-18
22   2026-03-19
23   2026-03-20
24   2026-03-21
25   2026-03-22
26   2026-03-23
27   2026-03-24
28   2026-03-25
29   2026-03-26
30   2026-03-27
31   2026-03-28
32   2026-03-29
33   2026-03-30
34   2026-03-31
35   2026-04-01
36   2026-04-02
37   2026-04-03
38   2026-04-04
39   2026-04-05
40   2026-04-06
41   2026-04-07
42   2026-04-08
43   2026-04-09
44   2026-04-10
45   2026-04-11
46   2026-04-12
47   2026-04-13
48   2026-04-14
49   2026-04-15
50          NaT
Name: Order_Date, dtype: datetime64[ns]

In [16]:
dates = pd.to_datetime(["2026-02-25", "2026-03-01", "2026-05-01"],format="%Y-%m-%d")
print(dates)

DatetimeIndex(['2026-02-25', '2026-03-01', '2026-05-01'], dtype='datetime64[ns]', freq=None)

In [18]:
dates = pd.to_datetime(["2026-02-25", "2026-03-01", "2026-05-01"],format="%Y-%m-%d")
print(dates)

DatetimeIndex(['2026-02-25', '2026-03-01', '2026-05-01'], dtype='datetime64[ns]', freq=None)

In [19]:
dates = pd.to_datetime(
    [
        "2026/05/01",
        "2026/20/08",
        "2026/20/ab"
    ],
    format="%Y/%d/%m",
    errors="coerce",
    utc=True
)

print(dates)

DatetimeIndex(['2026-01-05 00:00:00+00:00', '2026-08-20 00:00:00+00:00',
               'NaT'],
              dtype='datetime64[ns, UTC]', freq=None)