In [1]:
import pandas as pd

In [2]:
data = {
    "Names": ["Hemanth", "Uma Mahesh", "Sai Ram", "Ayapa", "Yasin"],
    "Age": [22,22,24,23,26],
    "Marks": [100,90,89,85,94],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Delhi", "Hyderabad"]
}
df = pd.DataFrame(data)

In [3]:
print(df)

        Names  Age  Marks       City
0     Hemanth   22    100  Hyderabad
1  Uma Mahesh   22     90    Chennai
2     Sai Ram   24     89  Bangalore
3       Ayapa   23     85      Delhi
4       Yasin   26     94  Hyderabad

In [5]:
print(df.shape)

(5, 4)

In [19]:
print(df.columns)

Index(['Names', 'Age', 'Marks', 'City'], dtype='object')

In [15]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Names   5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
 3   City    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None

In [20]:
print(df.index)

RangeIndex(start=0, stop=5, step=1)

In [21]:
print(df.dtypes)

Names    object
Age       int64
Marks     int64
City     object
dtype: object

In [10]:
print(df.head(3))

        Names  Age  Marks       City
0     Hemanth   22    100  Hyderabad
1  Uma Mahesh   22     90    Chennai
2     Sai Ram   24     89  Bangalore

In [11]:
print(df.tail(2))

   Names  Age  Marks       City
3  Ayapa   23     85      Delhi
4  Yasin   26     94  Hyderabad

In [16]:
print(df.describe())

            Age       Marks
count   5.00000    5.000000
mean   23.40000   91.600000
std     1.67332    5.683309
min    22.00000   85.000000
25%    22.00000   89.000000
50%    23.00000   90.000000
75%    24.00000   94.000000
max    26.00000  100.000000

In [22]:
df["Names"]

0       Hemanth
1    Uma Mahesh
2       Sai Ram
3         Ayapa
4         Yasin
Name: Names, dtype: object

In [24]:
df["Marks"]

0    100
1     90
2     89
3     85
4     94
Name: Marks, dtype: int64

In [25]:
df["Age"]

0    22
1    22
2    24
3    23
4    26
Name: Age, dtype: int64

In [27]:
df["City"]

0    Hyderabad
1      Chennai
2    Bangalore
3        Delhi
4    Hyderabad
Name: City, dtype: object

In [28]:
df[["Names","Marks"]]

        Names  Marks
0     Hemanth    100
1  Uma Mahesh     90
2     Sai Ram     89
3       Ayapa     85
4       Yasin     94

In [ ]:
#iloc- integer-location based selection, select based on position/index number
#first row
df.iloc[0]

Names      Hemanth
Age             22
Marks          100
City     Hyderabad
Name: 0, dtype: object

In [30]:
#second row
df.iloc[1]

Names    Uma Mahesh
Age              22
Marks            90
City        Chennai
Name: 1, dtype: object

In [31]:
df.iloc[0:3]

        Names  Age  Marks       City
0     Hemanth   22    100  Hyderabad
1  Uma Mahesh   22     90    Chennai
2     Sai Ram   24     89  Bangalore

In [32]:
df.iloc[0:3,[0,2]]

        Names  Marks
0     Hemanth    100
1  Uma Mahesh     90
2     Sai Ram     89

In [33]:
df.iloc[0:3,[0,2,3]]

        Names  Marks       City
0     Hemanth    100  Hyderabad
1  Uma Mahesh     90    Chennai
2     Sai Ram     89  Bangalore

In [35]:
df.loc[0]

Names      Hemanth
Age             22
Marks          100
City     Hyderabad
Name: 0, dtype: object

In [36]:
df2 = df.copy()

df2.index = ["A", "B", "C", "D", "E"]

In [37]:
print(df2)

        Names  Age  Marks       City
A     Hemanth   22    100  Hyderabad
B  Uma Mahesh   22     90    Chennai
C     Sai Ram   24     89  Bangalore
D       Ayapa   23     85      Delhi
E       Yasin   26     94  Hyderabad

In [41]:
df2.loc["B"]

Names    Uma Mahesh
Age              22
Marks            90
City        Chennai
Name: B, dtype: object

In [43]:
df2.iloc[1]

Names    Uma Mahesh
Age              22
Marks            90
City        Chennai
Name: B, dtype: object

In [44]:
df.loc[0:2,["Names", "Marks"]]

        Names  Marks
0     Hemanth    100
1  Uma Mahesh     90
2     Sai Ram     89

In [47]:
df2.loc["A":"C"]

        Names  Age  Marks       City
A     Hemanth   22    100  Hyderabad
B  Uma Mahesh   22     90    Chennai
C     Sai Ram   24     89  Bangalore

In [48]:
df2.loc[::-1]

        Names  Age  Marks       City
E       Yasin   26     94  Hyderabad
D       Ayapa   23     85      Delhi
C     Sai Ram   24     89  Bangalore
B  Uma Mahesh   22     90    Chennai
A     Hemanth   22    100  Hyderabad

In [3]:
df = pd.DataFrame({
    "org_name": ["google", "oracle", "infosys", "jp morgan", "deloitte"],
    "dept": ["IT", "HR", "SALES", "MARKETING", "MANAGING"],
    "type": ["product", "product", "service", "service", "service"],
    "salary": [100000, 80000, 50000, 90000, 35000]
}, index=["c1", "c2", "c3", "c4", "c5"])

In [4]:
print(df)

     org_name       dept     type  salary
c1     google         IT  product  100000
c2     oracle         HR  product   80000
c3    infosys      SALES  service   50000
c4  jp morgan  MARKETING  service   90000
c5   deloitte   MANAGING  service   35000

In [8]:
#boolean filtering
sal = df["salary"] > 50000
print(sal)
print(df[sal])

c1     True
c2     True
c3    False
c4     True
c5    False
Name: salary, dtype: bool
     org_name       dept     type  salary
c1     google         IT  product  100000
c2     oracle         HR  product   80000
c4  jp morgan  MARKETING  service   90000

In [ ]:
#Boolean - AND
con = (df["dept"] == 'IT') & (df["salary"] > 50000)
print(df[con])

   org_name dept     type  salary
c1   google   IT  product  100000

In [ ]:
#Boolean - OR
con = (df["dept"] == 'IT') | (df["salary"] > 50000)
print(df[con])

     org_name       dept     type  salary
c1     google         IT  product  100000
c2     oracle         HR  product   80000
c4  jp morgan  MARKETING  service   90000

In [ ]:
#Boolean - NOT
con = df[~(df["dept"] == 'IT') ]
print(con)

     org_name       dept     type  salary
c2     oracle         HR  product   80000
c3    infosys      SALES  service   50000
c4  jp morgan  MARKETING  service   90000
c5   deloitte   MANAGING  service   35000

In [15]:
#Boolean - Greater Than
con = df["salary"] > 50000
print(df[con])

     org_name       dept     type  salary
c1     google         IT  product  100000
c2     oracle         HR  product   80000
c4  jp morgan  MARKETING  service   90000

In [16]:
#Boolean - less Than
con = df["salary"] < 50000
print(df[con])

    org_name      dept     type  salary
c5  deloitte  MANAGING  service   35000

Dupilicates

In [3]:
data = pd.read_csv("./orders2.csv")

In [4]:
data.head()

,Order_ID,Order_Date,Customer_ID,Product,Category,Quantity,Price,City,Revenue
0,ORD051,2026-02-25,CUST051,Laptop,Electronics,1.0,72000.0,Hyderabad,72000.0
1,ORD052,2026-02-26,CUST052,Wireless Mouse,Accessories,2.0,1400.0,Bangalore,2800.0
2,ORD053,2026-02-27,CUST053,Keyboard,Accessories,NaN,2800.0,Chennai,NaN
3,ORD054,2026-02-28,CUST054,Monitor,Electronics,1.0,NaN,Mumbai,NaN
4,ORD055,2026-03-01,CUST055,Headphones,Audio,2.0,4200.0,NaN,8400.0

In [5]:
print(data.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
dtype: bool

In [6]:
data = pd.read_csv("./orders-dup.csv")

In [7]:
data.head()

,Order_ID,Order_Date,Customer_ID,Product,Category,Quantity,Price,City
0,ORD101,2026-05-01,CUST101,Laptop,Electronics,1,70000,Hyderabad
1,ORD102,2026-05-02,CUST102,Wireless Mouse,Accessories,2,1500,Bangalore
2,ORD103,2026-05-03,CUST103,Keyboard,Accessories,1,3000,Chennai
3,ORD104,2026-05-04,CUST104,Monitor,Electronics,1,20000,Mumbai
4,ORD105,2026-05-05,CUST105,Headphones,Audio,2,4000,Delhi

In [8]:
print(data.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
22     True
23     True
24     True
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [10]:
count = data.duplicated().sum()
print(count)

5

In [12]:
dup = data[data.duplicated()]
print(dup)

   Order_ID  Order_Date Customer_ID       Product     Category  Quantity  \
20   ORD105  2026-05-05     CUST105    Headphones        Audio         2
21   ORD110  2026-05-10     CUST110    Power Bank  Accessories         2
22   ORD115  2026-05-15     CUST115   Smart Watch    Wearables         1
23   ORD103  2026-05-03     CUST103      Keyboard  Accessories         1
24   ORD108  2026-05-08     CUST108  External SSD      Storage         1

    Price       City
20   4000      Delhi
21   2200     Mumbai
22   9500    Chennai
23   3000    Chennai
24   9000  Bangalore

In [14]:
data.duplicated(keep="first")
print(data.duplicated().sum())

5

In [15]:
data.duplicated(keep="last")

0     False
1     False
2      True
3     False
4      True
5     False
6     False
7      True
8     False
9      True
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool