In [ ]:
import pandas as pd

##Task -1

In [2]:
marks = pd.Series(
   [78, 92, 65, 88, 74, 95],
   index=["S101", "S102", "S103", "S104", "S105", "S106"],
   name="Marks"
)

In [ ]:
#1
print(marks)

S101    78
S102    92
S103    65
S104    88
S105    74
S106    95
Name: Marks, dtype: int64

In [ ]:
#2
print(marks.index)

Index(['S101', 'S102', 'S103', 'S104', 'S105', 'S106'], dtype='object')

In [5]:
print(marks.values)

[78 92 65 88 74 95]

In [6]:
print(marks.dtype)

int64

In [7]:
print(marks.shape)

(6,)

In [8]:
print(marks.size)

6

In [9]:
print(marks.ndim)

1

In [10]:
print(marks.name)

Marks

In [ ]:
#3
print(marks.mean())

82.0

In [ ]:
#4
print(marks.max())

95

In [ ]:
#5
print(marks.idxmax())

S106

In [20]:
#6
print(marks[marks>80])

S102    92
S104    88
S106    95
Name: Marks, dtype: int64

In [22]:
marks.iloc[0:3]

S101    78
S102    92
S103    65
Name: Marks, dtype: int64

In [24]:
print(marks.loc["S104"])

88

In [ ]:
#challenge
total = marks.sum()
per= (marks/total) *100
print(per)

S101    15.853659
S102    18.699187
S103    13.211382
S104    17.886179
S105    15.040650
S106    19.308943
Name: Marks, dtype: float64

In [28]:
stu = (marks/100)*100
print(stu)

S101    78.0
S102    92.0
S103    65.0
S104    88.0
S105    74.0
S106    95.0
Name: Marks, dtype: float64

*Task- 2*

In [53]:
prices = pd.Series(
        [1200, 850, 2300, 1750, 950, 3200],
        index=["P101", "P102", "P103", "P104", "P105", "P106"],
        name="Price"
        )

In [54]:
print(prices)

P101    1200
P102     850
P103    2300
P104    1750
P105     950
P106    3200
Name: Price, dtype: int64

In [55]:
#9
total = prices.sum()
print(total)

10250

In [56]:
#10
print(prices.mean())

1708.3333333333333

In [57]:
#11
print(prices.min())

850

In [58]:
#12
print(prices.max())

3200

In [59]:
#13
print(prices.idxmax(0))

P106

In [60]:
#14
print(prices[prices>1500])

P103    2300
P104    1750
P106    3200
Name: Price, dtype: int64

In [61]:
#15
print(prices[(1000<prices) & (prices<2500)])

P101    1200
P103    2300
P104    1750
Name: Price, dtype: int64

In [62]:
#16
prices = prices*1.10
print(prices)

P101    1320.0
P102     935.0
P103    2530.0
P104    1925.0
P105    1045.0
P106    3520.0
Name: Price, dtype: float64

In [65]:
#17
print(prices.nlargest(3))

P106    3520.0
P103    2530.0
P104    1925.0
Name: Price, dtype: float64

In [66]:
employees = pd.DataFrame({
    "EmpID": ["E101", "E102", "E103", "E104", "E105"],  
    "Name": ["Rahul", "Priya", "Arun", "Meena", "Kiran"],    
    "Age": [25, 29, 24, 32, 27],    
    "Department": ["IT", "HR", "IT", "Sales", "Finance"],    
    "Salary": [45000, 55000, 48000, 70000, 85000]})

In [ ]:
#18
print(employees)

  EmpID   Name  Age Department  Salary
0  E101  Rahul   25         IT   45000
1  E102  Priya   29         HR   55000
2  E103   Arun   24         IT   48000
3  E104  Meena   32      Sales   70000
4  E105  Kiran   27    Finance   85000

In [ ]:
#19
print(employees.shape)

(5, 5)

In [69]:
print(employees.size)

25

In [70]:
print(employees.ndim)

2

In [73]:
print(employees.index)

RangeIndex(start=0, stop=5, step=1)

In [74]:
print(employees.columns)

Index(['EmpID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [75]:
print(employees.values)

[['E101' 'Rahul' 25 'IT' 45000]
 ['E102' 'Priya' 29 'HR' 55000]
 ['E103' 'Arun' 24 'IT' 48000]
 ['E104' 'Meena' 32 'Sales' 70000]
 ['E105' 'Kiran' 27 'Finance' 85000]]

In [76]:
print(employees.dtypes)

EmpID         object
Name          object
Age            int64
Department    object
Salary         int64
dtype: object

In [ ]:
#20
print(employees["Name"])

0    Rahul
1    Priya
2     Arun
3    Meena
4    Kiran
Name: Name, dtype: object

In [ ]:
#21
print(employees[["Name", "Salary"]])

    Name  Salary
0  Rahul   45000
1  Priya   55000
2   Arun   48000
3  Meena   70000
4  Kiran   85000

In [88]:
#22
print(employees.iloc[0:3])

  EmpID   Name  Age Department  Salary
0  E101  Rahul   25         IT   45000
1  E102  Priya   29         HR   55000
2  E103   Arun   24         IT   48000

In [ ]:
#23
print(employees.iloc[:2:-1])

  EmpID   Name  Age Department  Salary
4  E105  Kiran   27    Finance   85000
3  E104  Meena   32      Sales   70000

In [97]:
#24
print(employees.iloc[1])

EmpID          E102
Name          Priya
Age              29
Department       HR
Salary        55000
Name: 1, dtype: object

In [98]:
#25
print(employees.iloc[1]["Salary"])

55000

In [4]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("./orders2.csv")
print(data.head())

  Order_ID  Order_Date Customer_ID         Product     Category  Quantity  \
0   ORD051  2026-02-25     CUST051          Laptop  Electronics       1.0
1   ORD052  2026-02-26     CUST052  Wireless Mouse  Accessories       2.0
2   ORD053  2026-02-27     CUST053        Keyboard  Accessories       NaN
3   ORD054  2026-02-28     CUST054         Monitor  Electronics       1.0
4   ORD055  2026-03-01     CUST055      Headphones        Audio       2.0

     Price       City  Revenue
0  72000.0  Hyderabad  72000.0
1   1400.0  Bangalore   2800.0
2   2800.0    Chennai      NaN
3      NaN     Mumbai      NaN
4   4200.0        NaN   8400.0

In [5]:
messy = data.copy()
print(messy.head())

  Order_ID  Order_Date Customer_ID         Product     Category  Quantity  \
0   ORD051  2026-02-25     CUST051          Laptop  Electronics       1.0
1   ORD052  2026-02-26     CUST052  Wireless Mouse  Accessories       2.0
2   ORD053  2026-02-27     CUST053        Keyboard  Accessories       NaN
3   ORD054  2026-02-28     CUST054         Monitor  Electronics       1.0
4   ORD055  2026-03-01     CUST055      Headphones        Audio       2.0

     Price       City  Revenue
0  72000.0  Hyderabad  72000.0
1   1400.0  Bangalore   2800.0
2   2800.0    Chennai      NaN
3      NaN     Mumbai      NaN
4   4200.0        NaN   8400.0

In [7]:
miss_per = ( messy.isna().mean() *100)
print(miss_per)

Order_ID        1.960784
Order_Date      1.960784
Customer_ID     7.843137
Product         1.960784
Category        3.921569
Quantity       15.686275
Price          11.764706
City           11.764706
Revenue        25.490196
dtype: float64

In [10]:
total_missing = messy.isna().sum()
print(total_missing)
total = total_missing.sum()
print(total)

Order_ID        1
Order_Date      1
Customer_ID     4
Product         1
Category        2
Quantity        8
Price           6
City            6
Revenue        13
dtype: int64
42

In [12]:
rows_missing = messy[messy.isna().any(axis=1)]
print(rows_missing.count())

Order_ID       21
Order_Date     21
Customer_ID    18
Product        21
Category       20
Quantity       14
Price          16
City           16
Revenue         9
dtype: int64

In [13]:
blank = messy[messy.isna().all(axis=1)]
print(blank)

   Order_ID Order_Date Customer_ID Product Category  Quantity  Price City  \
50      NaN        NaN         NaN     NaN      NaN       NaN    NaN  NaN

    Revenue
50      NaN

In [16]:
clean = messy.dropna()
print(clean.shape)
print(clean)

(29, 9)
   Order_ID  Order_Date Customer_ID              Product            Category  \
0    ORD051  2026-02-25     CUST051               Laptop         Electronics
1    ORD052  2026-02-26     CUST052       Wireless Mouse         Accessories
5    ORD056  2026-03-02     CUST056            USB Cable         Accessories
7    ORD058  2026-03-04     CUST058         External SSD             Storage
9    ORD060  2026-03-06     CUST060           Power Bank         Accessories
11   ORD062  2026-03-08     CUST062  Mechanical Keyboard         Accessories
13   ORD064  2026-03-10     CUST064               Tablet         Electronics
15   ORD066  2026-03-12     CUST066     Wireless Earbuds               Audio
16   ORD067  2026-03-13     CUST067           HDMI Cable         Accessories
18   ORD069  2026-03-15     CUST069         Office Chair           Furniture
19   ORD070  2026-03-16     CUST070            Mouse Pad         Accessories
21   ORD072  2026-03-18     CUST072              Printer         Electronics
23   ORD074  2026-03-20     CUST074               Router          Networking
25   ORD076  2026-03-22     CUST076     Screen Protector         Accessories
26   ORD077  2026-03-23     CUST077        Power Adapter         Accessories
28   ORD079  2026-03-25     CUST079    Gaming Controller              Gaming
29   ORD080  2026-03-26     CUST080           Microphone               Audio
30   ORD081  2026-03-27     CUST081             Smart TV         Electronics
33   ORD084  2026-03-30     CUST084      Graphics Tablet         Electronics
34   ORD085  2026-03-31     CUST085        WiFi Extender          Networking
36   ORD087  2026-04-02     CUST087           Smart Bulb          Smart Home
38   ORD089  2026-04-04     CUST089          DSLR Camera             Cameras
39   ORD090  2026-04-05     CUST090        Camera Tripod  Camera Accessories
40   ORD091  2026-04-06     CUST091          Memory Card             Storage
42   ORD093  2026-04-08     CUST093           VR Headset              Gaming
44   ORD095  2026-04-10     CUST095     Projector Screen       Home & Office
46   ORD097  2026-04-12     CUST097      USB Flash Drive             Storage
48   ORD099  2026-04-14     CUST099      Security Camera            Security
49   ORD100  2026-04-15     CUST100       Smart Home Hub          Smart Home

    Quantity    Price       City  Revenue
0        1.0  72000.0  Hyderabad  72000.0
1        2.0   1400.0  Bangalore   2800.0
5        4.0    700.0       Pune   2800.0
7        1.0   8500.0  Bangalore   8500.0
9        2.0   2100.0     Mumbai   4200.0
11       1.0   6200.0       Pune   6200.0
13       1.0  31000.0  Bangalore  31000.0
15       2.0   4800.0     Mumbai   9600.0
16       3.0   1000.0      Delhi   3000.0
18       1.0  13800.0  Hyderabad  13800.0
19       2.0    850.0  Bangalore   1700.0
21       1.0  16800.0     Mumbai  16800.0
23       1.0   4600.0       Pune   4600.0
25       3.0    550.0  Hyderabad   1650.0
26       1.0   2600.0  Bangalore   2600.0
28       2.0   5200.0     Mumbai  10400.0
29       1.0   7200.0      Delhi   7200.0
30       1.0  58000.0       Pune  58000.0
33       1.0   7800.0    Chennai   7800.0
34       1.0   3200.0     Mumbai   3200.0
36       4.0    950.0       Pune   3800.0
38       1.0  71000.0  Hyderabad  71000.0
39       1.0   3800.0  Bangalore   3800.0
40       2.0   1750.0    Chennai   3500.0
42       1.0  35000.0      Delhi  35000.0
44       1.0   7200.0  Hyderabad   7200.0
46       4.0   1250.0  Bangalore   5000.0
48       2.0   6900.0     Mumbai  13800.0
49       1.0   5900.0      Delhi   5900.0

In [19]:
clean_reveune = messy.dropna(subset=["Quantity", "Price"])
print(clean_reveune)

   Order_ID  Order_Date Customer_ID                      Product  \
0    ORD051  2026-02-25     CUST051                       Laptop
1    ORD052  2026-02-26     CUST052               Wireless Mouse
4    ORD055  2026-03-01     CUST055                   Headphones
5    ORD056  2026-03-02     CUST056                    USB Cable
6    ORD057  2026-03-03         NaN                       Webcam
7    ORD058  2026-03-04     CUST058                 External SSD
9    ORD060  2026-03-06     CUST060                   Power Bank
10   ORD061  2026-03-07     CUST061                 Laptop Stand
11   ORD062  2026-03-08     CUST062          Mechanical Keyboard
13   ORD064  2026-03-10     CUST064                       Tablet
14   ORD065  2026-03-11     CUST065                  Smart Watch
15   ORD066  2026-03-12     CUST066             Wireless Earbuds
16   ORD067  2026-03-13     CUST067                   HDMI Cable
18   ORD069  2026-03-15     CUST069                 Office Chair
19   ORD070  2026-03-16     CUST070                    Mouse Pad
21   ORD072  2026-03-18     CUST072                      Printer
23   ORD074  2026-03-20     CUST074                       Router
24   ORD075  2026-03-21     CUST075              Smartphone Case
25   ORD076  2026-03-22     CUST076             Screen Protector
26   ORD077  2026-03-23     CUST077                Power Adapter
27   ORD078  2026-03-24         NaN          Portable Hard Drive
28   ORD079  2026-03-25     CUST079            Gaming Controller
29   ORD080  2026-03-26     CUST080                   Microphone
30   ORD081  2026-03-27     CUST081                     Smart TV
33   ORD084  2026-03-30     CUST084              Graphics Tablet
34   ORD085  2026-03-31     CUST085                WiFi Extender
36   ORD087  2026-04-02     CUST087                   Smart Bulb
37   ORD088  2026-04-03     CUST088                  Power Strip
38   ORD089  2026-04-04     CUST089                  DSLR Camera
39   ORD090  2026-04-05     CUST090                Camera Tripod
40   ORD091  2026-04-06     CUST091                  Memory Card
42   ORD093  2026-04-08     CUST093                   VR Headset
44   ORD095  2026-04-10     CUST095             Projector Screen
45   ORD096  2026-04-11     CUST096  Noise Cancelling Headphones
46   ORD097  2026-04-12     CUST097              USB Flash Drive
47   ORD098  2026-04-13         NaN               Smart Doorbell
48   ORD099  2026-04-14     CUST099              Security Camera
49   ORD100  2026-04-15     CUST100               Smart Home Hub

              Category  Quantity    Price       City  Revenue
0          Electronics       1.0  72000.0  Hyderabad  72000.0
1          Accessories       2.0   1400.0  Bangalore   2800.0
4                Audio       2.0   4200.0        NaN   8400.0
5          Accessories       4.0    700.0       Pune   2800.0
6          Electronics       1.0   4500.0  Hyderabad   4500.0
7              Storage       1.0   8500.0  Bangalore   8500.0
9          Accessories       2.0   2100.0     Mumbai   4200.0
10                 NaN       1.0   2500.0      Delhi   2500.0
11         Accessories       1.0   6200.0       Pune   6200.0
13         Electronics       1.0  31000.0  Bangalore  31000.0
14           Wearables       1.0   9200.0        NaN   9200.0
15               Audio       2.0   4800.0     Mumbai   9600.0
16         Accessories       3.0   1000.0      Delhi   3000.0
18           Furniture       1.0  13800.0  Hyderabad  13800.0
19         Accessories       2.0    850.0  Bangalore   1700.0
21         Electronics       1.0  16800.0     Mumbai  16800.0
23          Networking       1.0   4600.0       Pune   4600.0
24         Accessories       2.0   1100.0        NaN   2200.0
25         Accessories       3.0    550.0  Hyderabad   1650.0
26         Accessories       1.0   2600.0  Bangalore   2600.0
27             Storage       1.0   6800.0    Chennai   6800.0
28              Gaming       2.0   5200.0     Mumbai  10400.0
29               Audio       1.0   7200.0      Delhi   7200.0
30         Electronics       1.0  58000.0       Pune  58000.0
33         Electronics       1.0   7800.0    Chennai   7800.0
34          Networking       1.0   3200.0     Mumbai   3200.0
36          Smart Home       4.0    950.0       Pune   3800.0
37         Accessories       2.0   1550.0        NaN   3100.0
38             Cameras       1.0  71000.0  Hyderabad  71000.0
39  Camera Accessories       1.0   3800.0  Bangalore   3800.0
40             Storage       2.0   1750.0    Chennai   3500.0
42              Gaming       1.0  35000.0      Delhi  35000.0
44       Home & Office       1.0   7200.0  Hyderabad   7200.0
45               Audio       1.0   9800.0        NaN   9800.0
46             Storage       4.0   1250.0  Bangalore   5000.0
47          Smart Home       1.0   8200.0    Chennai   8200.0
48            Security       2.0   6900.0     Mumbai  13800.0
49          Smart Home       1.0   5900.0      Delhi   5900.0

In [20]:
print(messy.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     50 non-null     object
 1   Order_Date   50 non-null     object
 2   Customer_ID  47 non-null     object
 3   Product      50 non-null     object
 4   Category     49 non-null     object
 5   Quantity     43 non-null     float64
 6   Price        45 non-null     float64
 7   City         45 non-null     object
 8   Revenue      38 non-null     float64
dtypes: float64(3), object(6)
memory usage: 3.7+ KB
None

In [23]:
messy["City"]= messy["City"].fillna("Unknown")
print(messy["City"])

0     Hyderabad
1     Bangalore
2       Chennai
3        Mumbai
4       Unknown
5          Pune
6     Hyderabad
7     Bangalore
8       Chennai
9        Mumbai
10        Delhi
11         Pune
12    Hyderabad
13    Bangalore
14      Unknown
15       Mumbai
16        Delhi
17         Pune
18    Hyderabad
19    Bangalore
20      Chennai
21       Mumbai
22        Delhi
23         Pune
24      Unknown
25    Hyderabad
26    Bangalore
27      Chennai
28       Mumbai
29        Delhi
30         Pune
31    Hyderabad
32    Bangalore
33      Chennai
34       Mumbai
35        Delhi
36         Pune
37      Unknown
38    Hyderabad
39    Bangalore
40      Chennai
41       Mumbai
42        Delhi
43         Pune
44    Hyderabad
45      Unknown
46    Bangalore
47      Chennai
48       Mumbai
49        Delhi
50      Unknown
Name: City, dtype: object

In [1]:
import pandas as pd
print(pd.__version__)

2.3.2

In [3]:
data = pd.read_csv("./Pandas_Dataset.csv")

In [4]:
data.head()

,Transaction_ID,Transaction_Date,Region,Category,Product,Customer_Segment,Quantity,Unit_Price,Revenue,Cost,Discount_Percent,Customer_Rating,Payment_Method
0,TXN0001,2025-08-03,East,Clothing,Shoes,Home Office,5,2896.10,14480.49,11108.36,20.0,2.9,Net Banking
1,TXN0002,2025-07-11,West,Groceries,Oil,Consumer,3,642.13,1926.39,1565.73,15.0,4.8,Credit Card
2,TXN0003,2025-06-19,West,Groceries,Coffee,Home Office,6,553.88,3323.27,1945.89,10.0,4.0,Debit Card
3,TXN0004,2025-11-25,East,Groceries,Snacks,Corporate,4,308.32,1233.27,729.05,10.0,4.2,Cash
4,TXN0005,2025-04-02,East,Electronics,Monitor,Home Office,6,16387.79,98326.73,64217.91,20.0,3.1,Cash

In [6]:
data.shape

(242, 13)

In [8]:
data.columns

Index(['Transaction_ID', 'Transaction_Date', 'Region', 'Category', 'Product',
       'Customer_Segment', 'Quantity', 'Unit_Price', 'Revenue', 'Cost',
       'Discount_Percent', 'Customer_Rating', 'Payment_Method'],
      dtype='object')

In [9]:
data.dtypes

Transaction_ID       object
Transaction_Date     object
Region               object
Category             object
Product              object
Customer_Segment     object
Quantity              int64
Unit_Price          float64
Revenue             float64
Cost                float64
Discount_Percent    float64
Customer_Rating     float64
Payment_Method       object
dtype: object

In [10]:
data.describe()

,Quantity,Unit_Price,Revenue,Cost,Discount_Percent,Customer_Rating
count,242.000000,242.000000,242.000000,242.000000,240.000000,239.000000
mean,4.041322,10322.179298,38927.208760,27191.241942,11.354167,3.733891
std,2.046743,15668.991597,68347.099212,47858.960943,6.575883,0.723366
min,1.000000,257.730000,257.730000,194.300000,0.000000,2.500000
25%,2.000000,856.407500,3497.757500,2465.900000,5.000000,3.100000
50%,4.000000,3246.585000,12483.485000,8856.110000,10.000000,3.800000
75%,6.000000,12531.182500,44240.565000,31006.142500,15.000000,4.300000
max,7.000000,73826.650000,485862.050000,350943.550000,20.000000,5.000000

In [11]:
data.nunique()

Transaction_ID      240
Transaction_Date    182
Region                7
Category              4
Product              16
Customer_Segment      3
Quantity              7
Unit_Price          240
Revenue             240
Cost                240
Discount_Percent      5
Customer_Rating      26
Payment_Method        8
dtype: int64

In [12]:
data.shape

(242, 13)

In [14]:
print(data.isna().sum())

Transaction_ID      0
Transaction_Date    0
Region              0
Category            0
Product             0
Customer_Segment    0
Quantity            0
Unit_Price          0
Revenue             0
Cost                0
Discount_Percent    2
Customer_Rating     3
Payment_Method      0
dtype: int64

In [16]:
print(data.isna().mean()*100)

Transaction_ID      0.000000
Transaction_Date    0.000000
Region              0.000000
Category            0.000000
Product             0.000000
Customer_Segment    0.000000
Quantity            0.000000
Unit_Price          0.000000
Revenue             0.000000
Cost                0.000000
Discount_Percent    0.826446
Customer_Rating     1.239669
Payment_Method      0.000000
dtype: float64

In [17]:
data.nunique()

Transaction_ID      240
Transaction_Date    182
Region                7
Category              4
Product              16
Customer_Segment      3
Quantity              7
Unit_Price          240
Revenue             240
Cost                240
Discount_Percent      5
Customer_Rating      26
Payment_Method        8
dtype: int64

In [18]:
quality_report = pd.DataFrame({
    "Data Type" : data.dtypes,
    "Missing Count": data.isna().sum(),
    "Missing Percentage" : data.isna().mean()*100,
    "Unique Values" : data.nunique()
})

print(quality_report)

                 Data Type  Missing Count  Missing Percentage  Unique Values
Transaction_ID      object              0            0.000000            240
Transaction_Date    object              0            0.000000            182
Region              object              0            0.000000              7
Category            object              0            0.000000              4
Product             object              0            0.000000             16
Customer_Segment    object              0            0.000000              3
Quantity             int64              0            0.000000              7
Unit_Price         float64              0            0.000000            240
Revenue            float64              0            0.000000            240
Cost               float64              0            0.000000            240
Discount_Percent   float64              2            0.826446              5
Customer_Rating    float64              3            1.239669             26
Payment_Method      object              0            0.000000              8

task 3

In [19]:
data["Region"].unique()

array(['East', 'West', 'South', 'south', 'North', 'WEST', 'North '],
      dtype=object)

In [21]:
data["Region"]= data["Region"].str.strip().str.title()
print(data['Region'].unique())

['East' 'West' 'South' 'North']

In [22]:
data["Region"].value_counts()

Region
North    78
East     55
South    55
West     54
Name: count, dtype: int64

task 4

In [23]:
data["Payment_Method"].unique()

array(['Net Banking', 'Credit Card', 'Debit Card', 'Cash', 'UPI', 'upi',
       'Credit card', 'UPI '], dtype=object)

In [24]:
data["Payment_Method"] = data["Payment_Method"].str.strip().str.title()

In [26]:
print(data["Payment_Method"].unique())

['Net Banking' 'Credit Card' 'Debit Card' 'Cash' 'Upi']

In [27]:
print(data["Payment_Method"].value_counts())

Payment_Method
Credit Card    53
Cash           52
Net Banking    48
Upi            47
Debit Card     42
Name: count, dtype: int64

In [29]:
print(data["Payment_Method"].count())

242

In [30]:
data[["Customer_Rating", "Discount_Percent"]].isna().sum()

Customer_Rating     3
Discount_Percent    2
dtype: int64

In [32]:
print(data["Customer_Rating"].median())

3.8

In [33]:
data["Customer_Rating"] = data["Customer_Rating"].fillna(data["Customer_Rating"].median())

In [35]:
print(data["Customer_Rating"].isna().sum())

0

In [36]:
data["Discount_Percent"] = data["Discount_Percent"].fillna(0)

In [37]:
print(data["Discount_Percent"].isna().sum())

0

In [38]:
data[["Customer_Rating", "Discount_Percent"]].isna().sum()

Customer_Rating     0
Discount_Percent    0
dtype: int64

Task 6

In [43]:
print(data.duplicated().sum())

2

In [45]:
print(data["Transaction_ID"].duplicated().sum())

2

In [46]:
print(data["Transaction_ID"].duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
237    False
238    False
239    False
240     True
241     True
Name: Transaction_ID, Length: 242, dtype: bool

In [47]:
data[data["Transaction_ID"].duplicated(keep=False)]

,Transaction_ID,Transaction_Date,Region,Category,Product,Customer_Segment,Quantity,Unit_Price,Revenue,Cost,Discount_Percent,Customer_Rating,Payment_Method
50,TXN0051,2025-10-11,South,Clothing,Jacket,Home Office,1,2424.93,2424.93,1964.31,10.0,2.7,Cash
151,TXN0152,2025-01-27,East,Electronics,Headphones,Consumer,4,3856.94,15427.78,11809.62,15.0,4.1,Cash
240,TXN0051,2025-10-11,South,Clothing,Jacket,Home Office,1,2424.93,2424.93,1964.31,10.0,2.7,Cash
241,TXN0152,2025-01-27,East,Electronics,Headphones,Consumer,4,3856.94,15427.78,11809.62,15.0,4.1,Cash

In [48]:
data = data.drop_duplicates(subset="Transaction_ID")

In [49]:
data[data["Transaction_ID"].duplicated(keep=False)]

Empty DataFrame
Columns: [Transaction_ID, Transaction_Date, Region, Category, Product, Customer_Segment, Quantity, Unit_Price, Revenue, Cost, Discount_Percent, Customer_Rating, Payment_Method]
Index: []

In [50]:
data.shape

(240, 13)

In [52]:
print(data["Transaction_ID"].duplicated().sum())

0

task7

In [53]:
filtered_data = data[
    (data["Revenue"] > 50000) &
    (data["Region"].isin(["North", "West"])) &
    (data["Quantity"] >= 5)
]

In [54]:
print(filtered_data)

    Transaction_ID Transaction_Date Region     Category       Product  \
14         TXN0015       2025-11-27   West    Furniture  Office Chair
16         TXN0017       2025-04-06   West  Electronics    Smartphone
27         TXN0028       2025-02-02   West  Electronics    Smartphone
31         TXN0032       2025-06-10   West    Furniture  Office Chair
43         TXN0044       2025-01-04   West    Furniture         Table
63         TXN0064       2025-05-26   West    Furniture          Desk
65         TXN0066       2025-01-23  North  Electronics       Monitor
77         TXN0078       2025-03-19   West  Electronics       Monitor
91         TXN0092       2025-02-11  North  Electronics        Laptop
98         TXN0099       2025-11-20  North  Electronics        Laptop
118        TXN0119       2025-12-29  North  Electronics    Smartphone
120        TXN0121       2025-09-07   West    Furniture          Desk
132        TXN0133       2025-10-20  North  Electronics        Laptop
145        TXN0146       2025-04-23  North    Furniture          Desk
159        TXN0160       2025-08-30   West  Electronics    Smartphone
162        TXN0163       2025-06-27   West    Furniture  Office Chair
174        TXN0175       2025-11-09   West    Furniture         Table
183        TXN0184       2025-04-08  North  Electronics       Monitor
199        TXN0200       2025-07-15  North    Furniture         Table
208        TXN0209       2025-01-14  North    Furniture          Desk
220        TXN0221       2025-07-11  North  Electronics       Monitor
225        TXN0226       2025-08-08  North  Electronics        Laptop
226        TXN0227       2025-06-18  North  Electronics    Smartphone

    Customer_Segment  Quantity  Unit_Price    Revenue       Cost  \
14         Corporate         5    10002.94   50014.72   38655.44
16          Consumer         5    33847.39  169236.93  109100.10
27       Home Office         5    28916.70  144583.49   96574.90
31       Home Office         7    10251.77   71762.42   56313.57
43       Home Office         7     9400.50   65803.53   52907.66
63       Home Office         6    15537.47   93224.81   55082.11
65          Consumer         7    16641.25  116488.75   90289.99
77         Corporate         7    15164.66  106152.61   85109.98
91         Corporate         5    59845.99  299229.95  219066.86
98          Consumer         7    69408.86  485862.05  350943.55
118      Home Office         5    30878.13  154390.65  108774.43
120      Home Office         7    14687.42  102811.93   82747.07
132         Consumer         6    55315.25  331891.52  229720.24
145         Consumer         5    14031.36   70156.82   40798.48
159         Consumer         7    31989.33  223925.28  163097.63
162        Corporate         7     9304.95   65134.64   42449.59
174        Corporate         6     9831.00   58985.98   40574.34
183        Corporate         5    16270.73   81353.67   58256.05
199         Consumer         5    12300.83   61504.15   38504.56
208      Home Office         5    13498.62   67493.09   53367.72
220         Consumer         5    14817.51   74087.55   56929.17
225      Home Office         6    71445.42  428672.53  255699.34
226        Corporate         7    29174.60  204222.18  124398.42

     Discount_Percent  Customer_Rating Payment_Method
14               15.0              3.5           Cash
16               10.0              3.3           Cash
27               10.0              4.1     Debit Card
31                0.0              3.5            Upi
43                0.0              3.8            Upi
63                0.0              4.4    Credit Card
65               20.0              5.0    Net Banking
77                5.0              4.4    Net Banking
91               15.0              3.3     Debit Card
98               15.0              3.9            Upi
118               5.0              2.9    Net Banking
120              20.0              3.7           Cash
132               0.0              3.2    Net Banking
145              20.0              4.0            Upi
159              15.0              3.4            Upi
162              15.0              4.7           Cash
174              10.0              4.9            Upi
183               0.0              2.8           Cash
199               0.0              3.1           Cash
208              10.0              4.5    Net Banking
220              20.0              2.8    Credit Card
225               5.0              2.6    Credit Card
226              15.0              4.4            Upi

In [55]:
print(filtered_data.shape)

(23, 13)

Task 8

In [56]:
data.sort_values("Revenue", ascending=False)

,Transaction_ID,Transaction_Date,Region,Category,Product,Customer_Segment,Quantity,Unit_Price,Revenue,Cost,Discount_Percent,Customer_Rating,Payment_Method
98,TXN0099,2025-11-20,North,Electronics,Laptop,Consumer,7,69408.86,485862.05,350943.55,15.0,3.9,Upi
225,TXN0226,2025-08-08,North,Electronics,Laptop,Home Office,6,71445.42,428672.53,255699.34,5.0,2.6,Credit Card
40,TXN0041,2025-03-17,South,Electronics,Laptop,Home Office,5,69638.99,348194.95,248278.66,20.0,3.5,Net Banking
80,TXN0081,2025-05-26,East,Electronics,Laptop,Home Office,5,66825.05,334125.26,248249.91,10.0,4.1,Upi
132,TXN0133,2025-10-20,North,Electronics,Laptop,Consumer,6,55315.25,331891.52,229720.24,0.0,3.2,Net Banking
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,TXN0061,2025-01-08,South,Groceries,Snacks,Corporate,1,337.37,337.37,273.30,15.0,2.8,Upi
189,TXN0190,2025-10-02,South,Groceries,Snacks,Corporate,1,313.92,313.92,210.71,15.0,4.8,Net Banking
205,TXN0206,2025-05-22,West,Groceries,Snacks,Consumer,1,309.76,309.76,217.34,15.0,4.3,Upi
126,TXN0127,2025-12-01,North,Groceries,Snacks,Home Office,1,271.25,271.25,194.30,5.0,3.3,Credit Card
181,TXN0182,2025-05-27,East,Groceries,Snacks,Corporate,1,257.73,257.73,207.07,15.0,4.2,Net Banking

In [57]:
data = data.sort_values("Revenue", ascending=False)

In [58]:
data["Profit"] = data["Revenue"] - data["Cost"]

In [59]:
print(data["Profit"])

98     134918.50
225    172973.19
40      99916.29
80      85875.35
132    102171.28
         ...
60         64.07
189       103.21
205        92.42
126        76.95
181        50.66
Name: Profit, Length: 240, dtype: float64

In [60]:
data.sort_values("Profit", ascending=False)

,Transaction_ID,Transaction_Date,Region,Category,Product,Customer_Segment,Quantity,Unit_Price,Revenue,Cost,Discount_Percent,Customer_Rating,Payment_Method,Profit
225,TXN0226,2025-08-08,North,Electronics,Laptop,Home Office,6,71445.42,428672.53,255699.34,5.0,2.6,Credit Card,172973.19
98,TXN0099,2025-11-20,North,Electronics,Laptop,Consumer,7,69408.86,485862.05,350943.55,15.0,3.9,Upi,134918.50
132,TXN0133,2025-10-20,North,Electronics,Laptop,Consumer,6,55315.25,331891.52,229720.24,0.0,3.2,Net Banking,102171.28
40,TXN0041,2025-03-17,South,Electronics,Laptop,Home Office,5,69638.99,348194.95,248278.66,20.0,3.5,Net Banking,99916.29
80,TXN0081,2025-05-26,East,Electronics,Laptop,Home Office,5,66825.05,334125.26,248249.91,10.0,4.1,Upi,85875.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,TXN0190,2025-10-02,South,Groceries,Snacks,Corporate,1,313.92,313.92,210.71,15.0,4.8,Net Banking,103.21
205,TXN0206,2025-05-22,West,Groceries,Snacks,Consumer,1,309.76,309.76,217.34,15.0,4.3,Upi,92.42
126,TXN0127,2025-12-01,North,Groceries,Snacks,Home Office,1,271.25,271.25,194.30,5.0,3.3,Credit Card,76.95
60,TXN0061,2025-01-08,South,Groceries,Snacks,Corporate,1,337.37,337.37,273.30,15.0,2.8,Upi,64.07
181,TXN0182,2025-05-27,East,Groceries,Snacks,Corporate,1,257.73,257.73,207.07,15.0,4.2,Net Banking,50.66

Task 9

In [62]:
print(data["Profit"].sum())

2836025.1900000004

In [63]:
print(data["Profit"].mean())

11816.771625000001

In [64]:
profit_margin = (
    data["Profit"].sum() /
    data["Revenue"].sum()
) * 100

In [65]:
print(profit_margin)

30.162356770585607

In [66]:
total_profit = data["Profit"].sum()
average_profit = data["Profit"].mean()
profit_margin = (data["Profit"].sum() / data["Revenue"].sum()) * 100

In [67]:
print(total_profit)

2836025.1900000004

In [68]:
print(average_profit)

11816.771625000001

In [69]:
print(profit_margin)

30.162356770585607

Task 10

In [70]:
data.groupby("Region")["Revenue"].sum()

Region
East     1801974.10
North    3233218.56
South    2054204.14
West     2313135.01
Name: Revenue, dtype: float64

In [71]:
data.groupby("Region")["Cost"].sum()

Region
East     1267152.47
North    2216529.77
South    1438355.22
West     1644469.16
Name: Cost, dtype: float64

In [72]:
data.groupby("Region")["Customer_Rating"].mean()

Region
East     3.783333
North    3.710256
South    3.598148
West     3.870370
Name: Customer_Rating, dtype: float64

In [73]:
region_summary = data.groupby("Region").agg(
    Total_Revenue=("Revenue", "sum"),
    Total_Cost=("Cost", "sum"),
    Total_Profit=("Profit", "sum"),
    Average_Rating=("Customer_Rating", "mean")
)

In [74]:
print(region_summary)

        Total_Revenue  Total_Cost  Total_Profit  Average_Rating
Region
East       1801974.10  1267152.47     534821.63        3.783333
North      3233218.56  2216529.77    1016688.79        3.710256
South      2054204.14  1438355.22     615848.92        3.598148
West       2313135.01  1644469.16     668665.85        3.870370

Task 11

In [75]:
region_category_summary = data.groupby(
    ["Region", "Category"]
).agg(
    Total_Revenue=("Revenue", "sum"),
    Total_Cost=("Cost", "sum"),
    Total_Profit=("Profit", "sum")
).reset_index()

In [76]:
print(region_category_summary)

   Region     Category  Total_Revenue  Total_Cost  Total_Profit
0    East     Clothing       90993.22    62160.56      28832.66
1    East  Electronics     1204820.29   876586.23     328234.06
2    East    Furniture      457433.14   294671.64     162761.50
3    East    Groceries       48727.45    33734.04      14993.41
4   North     Clothing      140567.76   100481.88      40085.88
5   North  Electronics     2510826.64  1724216.03     786610.61
6   North    Furniture      512729.66   343707.60     169022.06
7   North    Groceries       69094.50    48124.26      20970.24
8   South     Clothing      109951.01    74176.86      35774.15
9   South  Electronics     1307499.18   915951.36     391547.82
10  South    Furniture      601336.22   423919.18     177417.04
11  South    Groceries       35417.73    24307.82      11109.91
12   West     Clothing       53787.10    36268.56      17518.54
13   West  Electronics     1244182.60   886888.88     357293.72
14   West    Furniture      965843.47   686391.81     279451.66
15   West    Groceries       49321.84    34919.91      14401.93

In [77]:
data.groupby(["Region", "Category"])["Revenue"].sum()

Region  Category
East    Clothing         90993.22
        Electronics    1204820.29
        Furniture       457433.14
        Groceries        48727.45
North   Clothing        140567.76
        Electronics    2510826.64
        Furniture       512729.66
        Groceries        69094.50
South   Clothing        109951.01
        Electronics    1307499.18
        Furniture       601336.22
        Groceries        35417.73
West    Clothing         53787.10
        Electronics    1244182.60
        Furniture       965843.47
        Groceries        49321.84
Name: Revenue, dtype: float64

In [78]:
data.groupby(["Region", "Category"])["Cost"].sum()

Region  Category
East    Clothing         62160.56
        Electronics     876586.23
        Furniture       294671.64
        Groceries        33734.04
North   Clothing        100481.88
        Electronics    1724216.03
        Furniture       343707.60
        Groceries        48124.26
South   Clothing         74176.86
        Electronics     915951.36
        Furniture       423919.18
        Groceries        24307.82
West    Clothing         36268.56
        Electronics     886888.88
        Furniture       686391.81
        Groceries        34919.91
Name: Cost, dtype: float64

In [79]:
data.groupby(["Region", "Category"])["Profit"].sum()

Region  Category
East    Clothing        28832.66
        Electronics    328234.06
        Furniture      162761.50
        Groceries       14993.41
North   Clothing        40085.88
        Electronics    786610.61
        Furniture      169022.06
        Groceries       20970.24
South   Clothing        35774.15
        Electronics    391547.82
        Furniture      177417.04
        Groceries       11109.91
West    Clothing        17518.54
        Electronics    357293.72
        Furniture      279451.66
        Groceries       14401.93
Name: Profit, dtype: float64

In [80]:
print(region_category_summary)

   Region     Category  Total_Revenue  Total_Cost  Total_Profit
0    East     Clothing       90993.22    62160.56      28832.66
1    East  Electronics     1204820.29   876586.23     328234.06
2    East    Furniture      457433.14   294671.64     162761.50
3    East    Groceries       48727.45    33734.04      14993.41
4   North     Clothing      140567.76   100481.88      40085.88
5   North  Electronics     2510826.64  1724216.03     786610.61
6   North    Furniture      512729.66   343707.60     169022.06
7   North    Groceries       69094.50    48124.26      20970.24
8   South     Clothing      109951.01    74176.86      35774.15
9   South  Electronics     1307499.18   915951.36     391547.82
10  South    Furniture      601336.22   423919.18     177417.04
11  South    Groceries       35417.73    24307.82      11109.91
12   West     Clothing       53787.10    36268.56      17518.54
13   West  Electronics     1244182.60   886888.88     357293.72
14   West    Furniture      965843.47   686391.81     279451.66
15   West    Groceries       49321.84    34919.91      14401.93

Task 12

In [81]:
revenue_pivot = pd.pivot_table(
    data,
    values="Revenue",
    index="Region",
    columns="Category",
    aggfunc="sum"
)

revenue_pivot

Category   Clothing  Electronics  Furniture  Groceries
Region
East       90993.22   1204820.29  457433.14   48727.45
North     140567.76   2510826.64  512729.66   69094.50
South     109951.01   1307499.18  601336.22   35417.73
West       53787.10   1244182.60  965843.47   49321.84

In [82]:
rating_pivot = pd.pivot_table(
    data,
    values="Customer_Rating",
    index="Category",
    aggfunc="mean"
)

rating_pivot

             Customer_Rating
Category
Clothing            3.807547
Electronics         3.791525
Furniture           3.626230
Groceries           3.735821

In [83]:
profit_pivot = pd.pivot_table(
    data,
    values="Profit",
    index="Customer_Segment",
    columns="Region",
    aggfunc="sum"
)

profit_pivot

Region                 East      North      South       West
Customer_Segment
Consumer           80054.06  422584.15  229142.50  228929.83
Corporate         120363.55  271460.86  177455.46  277879.98
Home Office       334404.02  322643.78  209250.96  161856.04

In [84]:
pd.pivot_table(
    data,
    values="Revenue",
    index="Region",
    columns="Category",
    aggfunc="sum"
)

Category   Clothing  Electronics  Furniture  Groceries
Region
East       90993.22   1204820.29  457433.14   48727.45
North     140567.76   2510826.64  512729.66   69094.50
South     109951.01   1307499.18  601336.22   35417.73
West       53787.10   1244182.60  965843.47   49321.84