In [1]:
import pandas as pd
print(pd.__version__)

2.3.2

In [ ]:
# series is a basic one dimensional labeled collection of data in pandas
# the data looks like it has index and the related value to it
marks = pd.Series([85,90,79,99,100])
print(marks)

0     85
1     90
2     79
3     99
4    100
dtype: int64

In [4]:
#in series we can give the custom indexes also
marks = pd.Series([85,90,88,99], index=["python","SQL","Excel","PowerBI"])
print(marks)

python     85
SQL        90
Excel      88
PowerBI    99
dtype: int64

In [ ]:
#we can access th data using the custom indexes also 
print(marks["python"])

85

In [6]:
# data frame is basically a table, it has collection of series with same index
emp = {
    "Name" :["Hemanth","karthik", "Ganesh"],
    "Age" : [21,25,22],
    "salary" : [40000,50000,60000]
}
df = pd.DataFrame(emp)
print(df)

      Name  Age  salary
0  Hemanth   21   40000
1  karthik   25   50000
2   Ganesh   22   60000

In [7]:
df = pd.DataFrame( 
    emp,
    index = [101,102,103]
)
print(df)

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000
103   Ganesh   22   60000

In [8]:
print(df.shape)

(3, 3)

In [9]:
print(df.columns)

Index(['Name', 'Age', 'salary'], dtype='object')

In [10]:
print(df.index)

Index([101, 102, 103], dtype='int64')

In [11]:
print(df.dtypes)

Name      object
Age        int64
salary     int64
dtype: object

In [12]:
df.head()

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000
103   Ganesh   22   60000

In [13]:
df.head(2)

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000

In [14]:
df.tail()

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000
103   Ganesh   22   60000

In [15]:
df.tail(2)

        Name  Age  salary
102  karthik   25   50000
103   Ganesh   22   60000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 101 to 103
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 96.0+ bytes

In [17]:
df.describe()

             Age   salary
count   3.000000      3.0
mean   22.666667  50000.0
std     2.081666  10000.0
min    21.000000  40000.0
25%    21.500000  45000.0
50%    22.000000  50000.0
75%    23.500000  55000.0
max    25.000000  60000.0