In [1]:
import pandas as pd
print(pd.__version__)

2.3.2

In [2]:
# series is a basic one dimensional labeled collection of data in pandas
# the data looks like it has index and the related value to it
marks = pd.Series([85,90,79,99,100])
print(marks)

0     85
1     90
2     79
3     99
4    100
dtype: int64

In [3]:
#in series we can give the custom indexes also
marks = pd.Series([85,90,88,99], index=["python","SQL","Excel","PowerBI"])
print(marks)

python     85
SQL        90
Excel      88
PowerBI    99
dtype: int64

In [4]:
#we can access th data using the custom indexes also 
print(marks["python"])

85

In [5]:
# data frame is basically a table, it has collection of series with same index
emp = {
    "Name" :["Hemanth","karthik", "Ganesh"],
    "Age" : [21,25,22],
    "salary" : [40000,50000,60000]
}
df = pd.DataFrame(emp)
print(df)

      Name  Age  salary
0  Hemanth   21   40000
1  karthik   25   50000
2   Ganesh   22   60000

In [6]:
df = pd.DataFrame( 
    emp,
    index = [101,102,103]
)
print(df)

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000
103   Ganesh   22   60000

In [7]:
print(df.shape)

(3, 3)

In [8]:
print(df.columns)

Index(['Name', 'Age', 'salary'], dtype='object')

In [9]:
print(df.index)

Index([101, 102, 103], dtype='int64')

In [10]:
print(df.dtypes)

Name      object
Age        int64
salary     int64
dtype: object

In [11]:
df.head()

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000
103   Ganesh   22   60000

In [12]:
df.head(2)

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000

In [13]:
df.tail()

        Name  Age  salary
101  Hemanth   21   40000
102  karthik   25   50000
103   Ganesh   22   60000

In [14]:
df.tail(2)

        Name  Age  salary
102  karthik   25   50000
103   Ganesh   22   60000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 101 to 103
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 96.0+ bytes

In [16]:
df.describe()

             Age   salary
count   3.000000      3.0
mean   22.666667  50000.0
std     2.081666  10000.0
min    21.000000  40000.0
25%    21.500000  45000.0
50%    22.000000  50000.0
75%    23.500000  55000.0
max    25.000000  60000.0

In [18]:
marks = pd.Series([85,90,79,99,100])
print(marks)

0     85
1     90
2     79
3     99
4    100
dtype: int64

In [19]:
print(marks.mean())

90.6

In [20]:
print(marks.median())

90.0

In [21]:
print(marks.mode())

0     79
1     85
2     90
3     99
4    100
dtype: int64

In [22]:
print(marks.describe())

count      5.000000
mean      90.600000
std        9.016651
min       79.000000
25%       85.000000
50%       90.000000
75%       99.000000
max      100.000000
dtype: float64

In [23]:
print(marks.idxmax())

4

In [24]:
print(marks.idxmin())

2

In [27]:
print(marks.nlargest(4))

4    100
3     99
1     90
0     85
dtype: int64

In [28]:
print(marks.nsmallest(3))

2    79
0    85
1    90
dtype: int64

In [38]:
import numpy as np
arr = np.array([["101","102","103"],[22,23,24],[20000,30000,40000]])
print(arr)

[['101' '102' '103']
 ['22' '23' '24']
 ['20000' '30000' '40000']]

In [45]:
dataa = pd.DataFrame(
    arr,
    columns= ["EMPID","Age","Salay"]
)

In [46]:
print(dataa)

   EMPID    Age  Salay
0    101    102    103
1     22     23     24
2  20000  30000  40000

In [2]:
df = pd.DataFrame({
    "org_name": ["google", "oracle", "infosys", "jp morgan", "deloitte"],
    "dept": ["IT", "HR", "SALES", "MARKETING", "MANAGING"],
    "type": ["product", "product", "service", "service", "service"],
    "salary": [100000, 80000, 50000, 90000, 35000]
}, index=["c1", "c2", "c3", "c4", "c5"])

In [3]:
print(df[df["dept"].isin(["IT", "MANAGING"])]["org_name"])

c1      google
c5    deloitte
Name: org_name, dtype: object

In [4]:
df[df["type"] == "product"]

   org_name dept     type  salary
c1   google   IT  product  100000
c2   oracle   HR  product   80000

In [5]:
df[df["dept"].isin(["IT", "MANAGING"])]["org_name"]

c1      google
c5    deloitte
Name: org_name, dtype: object

In [6]:
df[df["salary"].between(50000, 100000, inclusive="neither")]

     org_name       dept     type  salary
c2     oracle         HR  product   80000
c4  jp morgan  MARKETING  service   90000

In [7]:
print(df.query("dept == 'IT'"))

   org_name dept     type  salary
c1   google   IT  product  100000

In [2]:
data = pd.read_csv("./orders.csv")
print(data)

   OrderID        Date CustomerID                  ProductName   Cost  \
0   ORD001  2026-01-05    CUST001                       Laptop  65000
1   ORD002  2026-01-06    CUST002               Wireless Mouse   1200
2   ORD003  2026-01-07    CUST003                     Keyboard   2500
3   ORD004  2026-01-08    CUST004                      Monitor  18500
4   ORD005  2026-01-09    CUST005                   Headphones   3500
5   ORD006  2026-01-10    CUST006                    USB Cable    650
6   ORD007  2026-01-11    CUST007                       Webcam   4200
7   ORD008  2026-01-12    CUST008                 External SSD   7800
8   ORD009  2026-01-13    CUST009                   Smartphone  42000
9   ORD010  2026-01-14    CUST010                   Power Bank   1800
10  ORD011  2026-01-15    CUST011                 Laptop Stand   2200
11  ORD012  2026-01-16    CUST012          Mechanical Keyboard   5500
12  ORD013  2026-01-17    CUST013            Bluetooth Speaker   3200
13  ORD014  2026-01-18    CUST014                       Tablet  28000
14  ORD015  2026-01-19    CUST015                  Smart Watch   8500
15  ORD016  2026-01-20    CUST016             Wireless Earbuds   4500
16  ORD017  2026-01-21    CUST017                   HDMI Cable    900
17  ORD018  2026-01-22    CUST018                    Desk Lamp   1600
18  ORD019  2026-01-23    CUST019                 Office Chair  12500
19  ORD020  2026-01-24    CUST020                    Mouse Pad    750
20  ORD021  2026-01-25    CUST021                   Laptop Bag   2800
21  ORD022  2026-01-26    CUST022                      Printer  15500
22  ORD023  2026-01-27    CUST023                Ink Cartridge   1800
23  ORD024  2026-01-28    CUST024                       Router   4200
24  ORD025  2026-01-29    CUST025              Smartphone Case    950
25  ORD026  2026-01-30    CUST026             Screen Protector    500
26  ORD027  2026-02-01    CUST027                Power Adapter   2400
27  ORD028  2026-02-02    CUST028          Portable Hard Drive   6200
28  ORD029  2026-02-03    CUST029            Gaming Controller   4800
29  ORD030  2026-02-04    CUST030                   Microphone   6500
30  ORD031  2026-02-05    CUST031                     Smart TV  52000
31  ORD032  2026-02-06    CUST032                     Soundbar  14500
32  ORD033  2026-02-07    CUST033                      USB Hub   1800
33  ORD034  2026-02-08    CUST034              Graphics Tablet   7200
34  ORD035  2026-02-09    CUST035                WiFi Extender   2800
35  ORD036  2026-02-10    CUST036                 Air Purifier  11500
36  ORD037  2026-02-11    CUST037                   Smart Bulb    850
37  ORD038  2026-02-12    CUST038                  Power Strip   1400
38  ORD039  2026-02-13    CUST039                  DSLR Camera  68000
39  ORD040  2026-02-14    CUST040                Camera Tripod   3500
40  ORD041  2026-02-15    CUST041                  Memory Card   1600
41  ORD042  2026-02-16    CUST042             Smartwatch Strap    900
42  ORD043  2026-02-17    CUST043                   VR Headset  32000
43  ORD044  2026-02-18    CUST044                    Projector  27500
44  ORD045  2026-02-19    CUST045             Projector Screen   6500
45  ORD046  2026-02-20    CUST046  Noise Cancelling Headphones   9200
46  ORD047  2026-02-21    CUST047              USB Flash Drive   1100
47  ORD048  2026-02-22    CUST048               Smart Doorbell   7800
48  ORD049  2026-02-23    CUST049              Security Camera   6500
49  ORD050  2026-02-24    CUST050               Smart Home Hub   5500

    Quantity
0          1
1          2
2          1
3          1
4          2
5          3
6          1
7          1
8          1
9          2
10         1
11         1
12         2
13         1
14         1
15         2
16         3
17         1
18         1
19         2
20         1
21         1
22         2
23         1
24         2
25         3
26         1
27         1
28         2
29         1
30         1
31         1
32         2
33         1
34         1
35         1
36         4
37         2
38         1
39         1
40         2
41         3
42         1
43         1
44         1
45         1
46         4
47         1
48         2
49         1

In [3]:
print(data.shape)

(50, 6)

In [19]:
print(data.tail())

   OrderID        Date CustomerID                  ProductName  Cost  Quantity
45  ORD046  2026-02-20    CUST046  Noise Cancelling Headphones  9200         1
46  ORD047  2026-02-21    CUST047              USB Flash Drive  1100         4
47  ORD048  2026-02-22    CUST048               Smart Doorbell  7800         1
48  ORD049  2026-02-23    CUST049              Security Camera  6500         2
49  ORD050  2026-02-24    CUST050               Smart Home Hub  5500         1

In [20]:
print(data.head())

  OrderID        Date CustomerID     ProductName   Cost  Quantity
0  ORD001  2026-01-05    CUST001          Laptop  65000         1
1  ORD002  2026-01-06    CUST002  Wireless Mouse   1200         2
2  ORD003  2026-01-07    CUST003        Keyboard   2500         1
3  ORD004  2026-01-08    CUST004         Monitor  18500         1
4  ORD005  2026-01-09    CUST005      Headphones   3500         2

In [22]:
print(data.sample())

   OrderID        Date CustomerID ProductName   Cost  Quantity
42  ORD043  2026-02-17    CUST043  VR Headset  32000         1

In [4]:
print(data.columns)

Index(['OrderID', 'Date', 'CustomerID', 'ProductName', 'Cost', 'Quantity'], dtype='object')

In [15]:
dual_order = data[data["Quantity"] > 1]
print(dual_order)

   OrderID        Date CustomerID        ProductName  Cost  Quantity
1   ORD002  2026-01-06    CUST002     Wireless Mouse  1200         2
4   ORD005  2026-01-09    CUST005         Headphones  3500         2
5   ORD006  2026-01-10    CUST006          USB Cable   650         3
9   ORD010  2026-01-14    CUST010         Power Bank  1800         2
12  ORD013  2026-01-17    CUST013  Bluetooth Speaker  3200         2
15  ORD016  2026-01-20    CUST016   Wireless Earbuds  4500         2
16  ORD017  2026-01-21    CUST017         HDMI Cable   900         3
19  ORD020  2026-01-24    CUST020          Mouse Pad   750         2
22  ORD023  2026-01-27    CUST023      Ink Cartridge  1800         2
24  ORD025  2026-01-29    CUST025    Smartphone Case   950         2
25  ORD026  2026-01-30    CUST026   Screen Protector   500         3
28  ORD029  2026-02-03    CUST029  Gaming Controller  4800         2
32  ORD033  2026-02-07    CUST033            USB Hub  1800         2
36  ORD037  2026-02-11    CUST037         Smart Bulb   850         4
37  ORD038  2026-02-12    CUST038        Power Strip  1400         2
40  ORD041  2026-02-15    CUST041        Memory Card  1600         2
41  ORD042  2026-02-16    CUST042   Smartwatch Strap   900         3
46  ORD047  2026-02-21    CUST047    USB Flash Drive  1100         4
48  ORD049  2026-02-23    CUST049    Security Camera  6500         2

In [17]:
print(data.describe())

            Cost   Quantity
count     50.000  50.000000
mean   10452.000   1.540000
std    15795.992   0.813408
min      500.000   1.000000
25%     1800.000   1.000000
50%     4350.000   1.000000
75%     9025.000   2.000000
max    68000.000   4.000000

In [27]:
print(data["Quantity"].sum())

77

In [31]:
print(data["Cost"].max())

68000

In [33]:
print(data.loc[data["Cost"].idxmax()])

OrderID             ORD039
Date            2026-02-13
CustomerID         CUST039
ProductName    DSLR Camera
Cost                 68000
Quantity                 1
Name: 38, dtype: object

In [35]:
print(data[data["Cost"] == data["Cost"].max()])

   OrderID        Date CustomerID  ProductName   Cost  Quantity
38  ORD039  2026-02-13    CUST039  DSLR Camera  68000         1